// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/identity/user/model"
	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

type UserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepository) EXPECT() *UserRepository_Expecter {
	return &UserRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, tx, input, passwordHash
func (_m *UserRepository) Create(ctx context.Context, tx *sqlx.Tx, input model.UserInput, passwordHash string) (model.User, error) {
	ret := _m.Called(ctx, tx, input, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, model.UserInput, string) (model.User, error)); ok {
		return rf(ctx, tx, input, passwordHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, model.UserInput, string) model.User); ok {
		r0 = rf(ctx, tx, input, passwordHash)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, model.UserInput, string) error); ok {
		r1 = rf(ctx, tx, input, passwordHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - input model.UserInput
//   - passwordHash string
func (_e *UserRepository_Expecter) Create(ctx interface{}, tx interface{}, input interface{}, passwordHash interface{}) *UserRepository_Create_Call {
	return &UserRepository_Create_Call{Call: _e.mock.On("Create", ctx, tx, input, passwordHash)}
}

func (_c *UserRepository_Create_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, input model.UserInput, passwordHash string)) *UserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(model.UserInput), args[3].(string))
	})
	return _c
}

func (_c *UserRepository_Create_Call) Return(_a0 model.User, _a1 error) *UserRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_Create_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, model.UserInput, string) (model.User, error)) *UserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, tx, id
func (_m *UserRepository) Delete(ctx context.Context, tx *sqlx.Tx, id string) error {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, string) error); ok {
		r0 = rf(ctx, tx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type UserRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - id string
func (_e *UserRepository_Expecter) Delete(ctx interface{}, tx interface{}, id interface{}) *UserRepository_Delete_Call {
	return &UserRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, tx, id)}
}

func (_c *UserRepository_Delete_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, id string)) *UserRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(string))
	})
	return _c
}

func (_c *UserRepository_Delete_Call) Return(_a0 error) *UserRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepository_Delete_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, string) error) *UserRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function with given fields: ctx, tx, email
func (_m *UserRepository) GetByEmail(ctx context.Context, tx *sqlx.Tx, email string) (model.User, error) {
	ret := _m.Called(ctx, tx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, string) (model.User, error)); ok {
		return rf(ctx, tx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, string) model.User); ok {
		r0 = rf(ctx, tx, email)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, string) error); ok {
		r1 = rf(ctx, tx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type UserRepository_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - email string
func (_e *UserRepository_Expecter) GetByEmail(ctx interface{}, tx interface{}, email interface{}) *UserRepository_GetByEmail_Call {
	return &UserRepository_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, tx, email)}
}

func (_c *UserRepository_GetByEmail_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, email string)) *UserRepository_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(string))
	})
	return _c
}

func (_c *UserRepository_GetByEmail_Call) Return(_a0 model.User, _a1 error) *UserRepository_GetByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_GetByEmail_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, string) (model.User, error)) *UserRepository_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, tx, id
func (_m *UserRepository) GetByID(ctx context.Context, tx *sqlx.Tx, id string) (model.User, error) {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, string) (model.User, error)); ok {
		return rf(ctx, tx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, string) model.User); ok {
		r0 = rf(ctx, tx, id)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, string) error); ok {
		r1 = rf(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type UserRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - id string
func (_e *UserRepository_Expecter) GetByID(ctx interface{}, tx interface{}, id interface{}) *UserRepository_GetByID_Call {
	return &UserRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, tx, id)}
}

func (_c *UserRepository_GetByID_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, id string)) *UserRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(string))
	})
	return _c
}

func (_c *UserRepository_GetByID_Call) Return(_a0 model.User, _a1 error) *UserRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_GetByID_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, string) (model.User, error)) *UserRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, tx, id, input
func (_m *UserRepository) Update(ctx context.Context, tx *sqlx.Tx, id string, input model.UserInput) (model.User, error) {
	ret := _m.Called(ctx, tx, id, input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, string, model.UserInput) (model.User, error)); ok {
		return rf(ctx, tx, id, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, string, model.UserInput) model.User); ok {
		r0 = rf(ctx, tx, id, input)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, string, model.UserInput) error); ok {
		r1 = rf(ctx, tx, id, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type UserRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - id string
//   - input model.UserInput
func (_e *UserRepository_Expecter) Update(ctx interface{}, tx interface{}, id interface{}, input interface{}) *UserRepository_Update_Call {
	return &UserRepository_Update_Call{Call: _e.mock.On("Update", ctx, tx, id, input)}
}

func (_c *UserRepository_Update_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, id string, input model.UserInput)) *UserRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(string), args[3].(model.UserInput))
	})
	return _c
}

func (_c *UserRepository_Update_Call) Return(_a0 model.User, _a1 error) *UserRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_Update_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, string, model.UserInput) (model.User, error)) *UserRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePasswordHash provides a mock function with given fields: ctx, tx, id, passwordHash
func (_m *UserRepository) UpdatePasswordHash(ctx context.Context, tx *sqlx.Tx, id string, passwordHash string) error {
	ret := _m.Called(ctx, tx, id, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePasswordHash")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, string, string) error); ok {
		r0 = rf(ctx, tx, id, passwordHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepository_UpdatePasswordHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePasswordHash'
type UserRepository_UpdatePasswordHash_Call struct {
	*mock.Call
}

// UpdatePasswordHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - id string
//   - passwordHash string
func (_e *UserRepository_Expecter) UpdatePasswordHash(ctx interface{}, tx interface{}, id interface{}, passwordHash interface{}) *UserRepository_UpdatePasswordHash_Call {
	return &UserRepository_UpdatePasswordHash_Call{Call: _e.mock.On("UpdatePasswordHash", ctx, tx, id, passwordHash)}
}

func (_c *UserRepository_UpdatePasswordHash_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, id string, passwordHash string)) *UserRepository_UpdatePasswordHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *UserRepository_UpdatePasswordHash_Call) Return(_a0 error) *UserRepository_UpdatePasswordHash_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepository_UpdatePasswordHash_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, string, string) error) *UserRepository_UpdatePasswordHash_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
