// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/identity/account/model"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// SessionCacheRepository is an autogenerated mock type for the SessionCacheRepository type
type SessionCacheRepository struct {
	mock.Mock
}

type SessionCacheRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionCacheRepository) EXPECT() *SessionCacheRepository_Expecter {
	return &SessionCacheRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, jti
func (_m *SessionCacheRepository) Delete(ctx context.Context, jti uuid.UUID) error {
	ret := _m.Called(ctx, jti)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, jti)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SessionCacheRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type SessionCacheRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - jti uuid.UUID
func (_e *SessionCacheRepository_Expecter) Delete(ctx interface{}, jti interface{}) *SessionCacheRepository_Delete_Call {
	return &SessionCacheRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, jti)}
}

func (_c *SessionCacheRepository_Delete_Call) Run(run func(ctx context.Context, jti uuid.UUID)) *SessionCacheRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *SessionCacheRepository_Delete_Call) Return(_a0 error) *SessionCacheRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SessionCacheRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *SessionCacheRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, jti
func (_m *SessionCacheRepository) Get(ctx context.Context, jti uuid.UUID) (model.Session, error) {
	ret := _m.Called(ctx, jti)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Session, error)); ok {
		return rf(ctx, jti)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Session); ok {
		r0 = rf(ctx, jti)
	} else {
		r0 = ret.Get(0).(model.Session)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, jti)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SessionCacheRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type SessionCacheRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - jti uuid.UUID
func (_e *SessionCacheRepository_Expecter) Get(ctx interface{}, jti interface{}) *SessionCacheRepository_Get_Call {
	return &SessionCacheRepository_Get_Call{Call: _e.mock.On("Get", ctx, jti)}
}

func (_c *SessionCacheRepository_Get_Call) Run(run func(ctx context.Context, jti uuid.UUID)) *SessionCacheRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *SessionCacheRepository_Get_Call) Return(_a0 model.Session, _a1 error) *SessionCacheRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SessionCacheRepository_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (model.Session, error)) *SessionCacheRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, jti, session, ttl
func (_m *SessionCacheRepository) Set(ctx context.Context, jti uuid.UUID, session model.Session, ttl time.Duration) error {
	ret := _m.Called(ctx, jti, session, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Session, time.Duration) error); ok {
		r0 = rf(ctx, jti, session, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SessionCacheRepository_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type SessionCacheRepository_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - jti uuid.UUID
//   - session model.Session
//   - ttl time.Duration
func (_e *SessionCacheRepository_Expecter) Set(ctx interface{}, jti interface{}, session interface{}, ttl interface{}) *SessionCacheRepository_Set_Call {
	return &SessionCacheRepository_Set_Call{Call: _e.mock.On("Set", ctx, jti, session, ttl)}
}

func (_c *SessionCacheRepository_Set_Call) Run(run func(ctx context.Context, jti uuid.UUID, session model.Session, ttl time.Duration)) *SessionCacheRepository_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Session), args[3].(time.Duration))
	})
	return _c
}

func (_c *SessionCacheRepository_Set_Call) Return(_a0 error) *SessionCacheRepository_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SessionCacheRepository_Set_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Session, time.Duration) error) *SessionCacheRepository_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewSessionCacheRepository creates a new instance of SessionCacheRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionCacheRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionCacheRepository {
	mock := &SessionCacheRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
