with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceNameSnake}}.go"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
resolve-type-alias: false
issue-845-fix: true
disable-version-string: true

# Моки генерируются только для internal (сервисы, репозитории).
# Для pkg/ не генерируем — в тестах обычно достаточно noop/реальных реализаций.
packages:
  # Identity — user
  github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/identity/user/service:
    config:
      include-regex: ".*Service"
  # User repository — адаптер
  github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/identity/user/repository:
    config:
      include-regex: ".*Repository"
  # User repository — контракты reader/writer
  github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/identity/user/repository/user:
    config:
      include-regex: ".*Repository"
  # User repository — контракт кеша
  github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/identity/user/repository/cache:
    config:
      include-regex: ".*Repository"

  # Identity — account
  github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/identity/account/service:
    config:
      include-regex: ".*Service"
  github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/identity/account/repository:
    config:
      include-regex: ".*Repository"

  # Team
  github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/team/service:
    config:
      include-regex: ".*Service"
  # Team repository — адаптер
  github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/team/repository:
    config:
      include-regex: ".*Repository"
  # Team repository — контракты reader/writer для teams
  github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/team/repository/team:
    config:
      include-regex: ".*Repository"
  # Team repository — контракты reader/writer для team_members
  github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/team/repository/member:
    config:
      include-regex: ".*Repository"
  # Team repository — контракты reader/writer для team_invitations
  github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/team/repository/invitation:
    config:
      include-regex: ".*Repository"
