// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/workspace/task/model"
	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"

	time "time"
)

// ReportReaderRepository is an autogenerated mock type for the ReportReaderRepository type
type ReportReaderRepository struct {
	mock.Mock
}

type ReportReaderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ReportReaderRepository) EXPECT() *ReportReaderRepository_Expecter {
	return &ReportReaderRepository_Expecter{mock: &_m.Mock}
}

// TasksWithInvalidAssignee provides a mock function with given fields: ctx, tx
func (_m *ReportReaderRepository) TasksWithInvalidAssignee(ctx context.Context, tx *sqlx.Tx) ([]*model.Task, error) {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for TasksWithInvalidAssignee")
	}

	var r0 []*model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx) ([]*model.Task, error)); ok {
		return rf(ctx, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx) []*model.Task); ok {
		r0 = rf(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx) error); ok {
		r1 = rf(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportReaderRepository_TasksWithInvalidAssignee_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TasksWithInvalidAssignee'
type ReportReaderRepository_TasksWithInvalidAssignee_Call struct {
	*mock.Call
}

// TasksWithInvalidAssignee is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
func (_e *ReportReaderRepository_Expecter) TasksWithInvalidAssignee(ctx interface{}, tx interface{}) *ReportReaderRepository_TasksWithInvalidAssignee_Call {
	return &ReportReaderRepository_TasksWithInvalidAssignee_Call{Call: _e.mock.On("TasksWithInvalidAssignee", ctx, tx)}
}

func (_c *ReportReaderRepository_TasksWithInvalidAssignee_Call) Run(run func(ctx context.Context, tx *sqlx.Tx)) *ReportReaderRepository_TasksWithInvalidAssignee_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx))
	})
	return _c
}

func (_c *ReportReaderRepository_TasksWithInvalidAssignee_Call) Return(_a0 []*model.Task, _a1 error) *ReportReaderRepository_TasksWithInvalidAssignee_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportReaderRepository_TasksWithInvalidAssignee_Call) RunAndReturn(run func(context.Context, *sqlx.Tx) ([]*model.Task, error)) *ReportReaderRepository_TasksWithInvalidAssignee_Call {
	_c.Call.Return(run)
	return _c
}

// TeamTaskStats provides a mock function with given fields: ctx, tx, since
func (_m *ReportReaderRepository) TeamTaskStats(ctx context.Context, tx *sqlx.Tx, since time.Time) ([]*model.TeamTaskStats, error) {
	ret := _m.Called(ctx, tx, since)

	if len(ret) == 0 {
		panic("no return value specified for TeamTaskStats")
	}

	var r0 []*model.TeamTaskStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, time.Time) ([]*model.TeamTaskStats, error)); ok {
		return rf(ctx, tx, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, time.Time) []*model.TeamTaskStats); ok {
		r0 = rf(ctx, tx, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.TeamTaskStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, time.Time) error); ok {
		r1 = rf(ctx, tx, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportReaderRepository_TeamTaskStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TeamTaskStats'
type ReportReaderRepository_TeamTaskStats_Call struct {
	*mock.Call
}

// TeamTaskStats is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - since time.Time
func (_e *ReportReaderRepository_Expecter) TeamTaskStats(ctx interface{}, tx interface{}, since interface{}) *ReportReaderRepository_TeamTaskStats_Call {
	return &ReportReaderRepository_TeamTaskStats_Call{Call: _e.mock.On("TeamTaskStats", ctx, tx, since)}
}

func (_c *ReportReaderRepository_TeamTaskStats_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, since time.Time)) *ReportReaderRepository_TeamTaskStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(time.Time))
	})
	return _c
}

func (_c *ReportReaderRepository_TeamTaskStats_Call) Return(_a0 []*model.TeamTaskStats, _a1 error) *ReportReaderRepository_TeamTaskStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportReaderRepository_TeamTaskStats_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, time.Time) ([]*model.TeamTaskStats, error)) *ReportReaderRepository_TeamTaskStats_Call {
	_c.Call.Return(run)
	return _c
}

// TopCreatorsByTeam provides a mock function with given fields: ctx, tx, since, limit
func (_m *ReportReaderRepository) TopCreatorsByTeam(ctx context.Context, tx *sqlx.Tx, since time.Time, limit int) ([]*model.TeamTopCreator, error) {
	ret := _m.Called(ctx, tx, since, limit)

	if len(ret) == 0 {
		panic("no return value specified for TopCreatorsByTeam")
	}

	var r0 []*model.TeamTopCreator
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, time.Time, int) ([]*model.TeamTopCreator, error)); ok {
		return rf(ctx, tx, since, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, time.Time, int) []*model.TeamTopCreator); ok {
		r0 = rf(ctx, tx, since, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.TeamTopCreator)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, time.Time, int) error); ok {
		r1 = rf(ctx, tx, since, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportReaderRepository_TopCreatorsByTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TopCreatorsByTeam'
type ReportReaderRepository_TopCreatorsByTeam_Call struct {
	*mock.Call
}

// TopCreatorsByTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - since time.Time
//   - limit int
func (_e *ReportReaderRepository_Expecter) TopCreatorsByTeam(ctx interface{}, tx interface{}, since interface{}, limit interface{}) *ReportReaderRepository_TopCreatorsByTeam_Call {
	return &ReportReaderRepository_TopCreatorsByTeam_Call{Call: _e.mock.On("TopCreatorsByTeam", ctx, tx, since, limit)}
}

func (_c *ReportReaderRepository_TopCreatorsByTeam_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, since time.Time, limit int)) *ReportReaderRepository_TopCreatorsByTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(time.Time), args[3].(int))
	})
	return _c
}

func (_c *ReportReaderRepository_TopCreatorsByTeam_Call) Return(_a0 []*model.TeamTopCreator, _a1 error) *ReportReaderRepository_TopCreatorsByTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportReaderRepository_TopCreatorsByTeam_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, time.Time, int) ([]*model.TeamTopCreator, error)) *ReportReaderRepository_TopCreatorsByTeam_Call {
	_c.Call.Return(run)
	return _c
}

// NewReportReaderRepository creates a new instance of ReportReaderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportReaderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportReaderRepository {
	mock := &ReportReaderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
