// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/team/model"
	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"
)

// InvitationReaderRepository is an autogenerated mock type for the InvitationReaderRepository type
type InvitationReaderRepository struct {
	mock.Mock
}

type InvitationReaderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *InvitationReaderRepository) EXPECT() *InvitationReaderRepository_Expecter {
	return &InvitationReaderRepository_Expecter{mock: &_m.Mock}
}

// GetPendingByTeamAndEmail provides a mock function with given fields: ctx, tx, teamID, email
func (_m *InvitationReaderRepository) GetPendingByTeamAndEmail(ctx context.Context, tx *sqlx.Tx, teamID string, email string) (*model.TeamInvitation, error) {
	ret := _m.Called(ctx, tx, teamID, email)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingByTeamAndEmail")
	}

	var r0 *model.TeamInvitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, string, string) (*model.TeamInvitation, error)); ok {
		return rf(ctx, tx, teamID, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, string, string) *model.TeamInvitation); ok {
		r0 = rf(ctx, tx, teamID, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TeamInvitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, string, string) error); ok {
		r1 = rf(ctx, tx, teamID, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InvitationReaderRepository_GetPendingByTeamAndEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingByTeamAndEmail'
type InvitationReaderRepository_GetPendingByTeamAndEmail_Call struct {
	*mock.Call
}

// GetPendingByTeamAndEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - teamID string
//   - email string
func (_e *InvitationReaderRepository_Expecter) GetPendingByTeamAndEmail(ctx interface{}, tx interface{}, teamID interface{}, email interface{}) *InvitationReaderRepository_GetPendingByTeamAndEmail_Call {
	return &InvitationReaderRepository_GetPendingByTeamAndEmail_Call{Call: _e.mock.On("GetPendingByTeamAndEmail", ctx, tx, teamID, email)}
}

func (_c *InvitationReaderRepository_GetPendingByTeamAndEmail_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, teamID string, email string)) *InvitationReaderRepository_GetPendingByTeamAndEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *InvitationReaderRepository_GetPendingByTeamAndEmail_Call) Return(_a0 *model.TeamInvitation, _a1 error) *InvitationReaderRepository_GetPendingByTeamAndEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InvitationReaderRepository_GetPendingByTeamAndEmail_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, string, string) (*model.TeamInvitation, error)) *InvitationReaderRepository_GetPendingByTeamAndEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewInvitationReaderRepository creates a new instance of InvitationReaderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInvitationReaderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InvitationReaderRepository {
	mock := &InvitationReaderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
