// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/workspace/task/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// TaskCommentService is an autogenerated mock type for the TaskCommentService type
type TaskCommentService struct {
	mock.Mock
}

type TaskCommentService_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskCommentService) EXPECT() *TaskCommentService_Expecter {
	return &TaskCommentService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, taskID, userID, content
func (_m *TaskCommentService) Create(ctx context.Context, taskID uuid.UUID, userID uuid.UUID, content string) (*model.TaskComment, error) {
	ret := _m.Called(ctx, taskID, userID, content)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.TaskComment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) (*model.TaskComment, error)); ok {
		return rf(ctx, taskID, userID, content)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) *model.TaskComment); ok {
		r0 = rf(ctx, taskID, userID, content)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TaskComment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = rf(ctx, taskID, userID, content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskCommentService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TaskCommentService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID uuid.UUID
//   - userID uuid.UUID
//   - content string
func (_e *TaskCommentService_Expecter) Create(ctx interface{}, taskID interface{}, userID interface{}, content interface{}) *TaskCommentService_Create_Call {
	return &TaskCommentService_Create_Call{Call: _e.mock.On("Create", ctx, taskID, userID, content)}
}

func (_c *TaskCommentService_Create_Call) Run(run func(ctx context.Context, taskID uuid.UUID, userID uuid.UUID, content string)) *TaskCommentService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *TaskCommentService_Create_Call) Return(_a0 *model.TaskComment, _a1 error) *TaskCommentService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskCommentService_Create_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string) (*model.TaskComment, error)) *TaskCommentService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ListByTaskID provides a mock function with given fields: ctx, taskID, userID
func (_m *TaskCommentService) ListByTaskID(ctx context.Context, taskID uuid.UUID, userID uuid.UUID) ([]*model.TaskComment, error) {
	ret := _m.Called(ctx, taskID, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByTaskID")
	}

	var r0 []*model.TaskComment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]*model.TaskComment, error)); ok {
		return rf(ctx, taskID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []*model.TaskComment); ok {
		r0 = rf(ctx, taskID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.TaskComment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, taskID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskCommentService_ListByTaskID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByTaskID'
type TaskCommentService_ListByTaskID_Call struct {
	*mock.Call
}

// ListByTaskID is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID uuid.UUID
//   - userID uuid.UUID
func (_e *TaskCommentService_Expecter) ListByTaskID(ctx interface{}, taskID interface{}, userID interface{}) *TaskCommentService_ListByTaskID_Call {
	return &TaskCommentService_ListByTaskID_Call{Call: _e.mock.On("ListByTaskID", ctx, taskID, userID)}
}

func (_c *TaskCommentService_ListByTaskID_Call) Run(run func(ctx context.Context, taskID uuid.UUID, userID uuid.UUID)) *TaskCommentService_ListByTaskID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TaskCommentService_ListByTaskID_Call) Return(_a0 []*model.TaskComment, _a1 error) *TaskCommentService_ListByTaskID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskCommentService_ListByTaskID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) ([]*model.TaskComment, error)) *TaskCommentService_ListByTaskID_Call {
	_c.Call.Return(run)
	return _c
}

// NewTaskCommentService creates a new instance of TaskCommentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskCommentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskCommentService {
	mock := &TaskCommentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
