// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/workspace/task/model"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// TaskReportService is an autogenerated mock type for the TaskReportService type
type TaskReportService struct {
	mock.Mock
}

type TaskReportService_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskReportService) EXPECT() *TaskReportService_Expecter {
	return &TaskReportService_Expecter{mock: &_m.Mock}
}

// TasksWithInvalidAssignee provides a mock function with given fields: ctx, userID
func (_m *TaskReportService) TasksWithInvalidAssignee(ctx context.Context, userID uuid.UUID) ([]*model.Task, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for TasksWithInvalidAssignee")
	}

	var r0 []*model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.Task, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.Task); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskReportService_TasksWithInvalidAssignee_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TasksWithInvalidAssignee'
type TaskReportService_TasksWithInvalidAssignee_Call struct {
	*mock.Call
}

// TasksWithInvalidAssignee is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *TaskReportService_Expecter) TasksWithInvalidAssignee(ctx interface{}, userID interface{}) *TaskReportService_TasksWithInvalidAssignee_Call {
	return &TaskReportService_TasksWithInvalidAssignee_Call{Call: _e.mock.On("TasksWithInvalidAssignee", ctx, userID)}
}

func (_c *TaskReportService_TasksWithInvalidAssignee_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *TaskReportService_TasksWithInvalidAssignee_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *TaskReportService_TasksWithInvalidAssignee_Call) Return(_a0 []*model.Task, _a1 error) *TaskReportService_TasksWithInvalidAssignee_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskReportService_TasksWithInvalidAssignee_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*model.Task, error)) *TaskReportService_TasksWithInvalidAssignee_Call {
	_c.Call.Return(run)
	return _c
}

// TeamTaskStats provides a mock function with given fields: ctx, userID, since
func (_m *TaskReportService) TeamTaskStats(ctx context.Context, userID uuid.UUID, since time.Time) ([]*model.TeamTaskStats, error) {
	ret := _m.Called(ctx, userID, since)

	if len(ret) == 0 {
		panic("no return value specified for TeamTaskStats")
	}

	var r0 []*model.TeamTaskStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) ([]*model.TeamTaskStats, error)); ok {
		return rf(ctx, userID, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) []*model.TeamTaskStats); ok {
		r0 = rf(ctx, userID, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.TeamTaskStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, userID, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskReportService_TeamTaskStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TeamTaskStats'
type TaskReportService_TeamTaskStats_Call struct {
	*mock.Call
}

// TeamTaskStats is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - since time.Time
func (_e *TaskReportService_Expecter) TeamTaskStats(ctx interface{}, userID interface{}, since interface{}) *TaskReportService_TeamTaskStats_Call {
	return &TaskReportService_TeamTaskStats_Call{Call: _e.mock.On("TeamTaskStats", ctx, userID, since)}
}

func (_c *TaskReportService_TeamTaskStats_Call) Run(run func(ctx context.Context, userID uuid.UUID, since time.Time)) *TaskReportService_TeamTaskStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *TaskReportService_TeamTaskStats_Call) Return(_a0 []*model.TeamTaskStats, _a1 error) *TaskReportService_TeamTaskStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskReportService_TeamTaskStats_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) ([]*model.TeamTaskStats, error)) *TaskReportService_TeamTaskStats_Call {
	_c.Call.Return(run)
	return _c
}

// TopCreatorsByTeam provides a mock function with given fields: ctx, userID, since, limit
func (_m *TaskReportService) TopCreatorsByTeam(ctx context.Context, userID uuid.UUID, since time.Time, limit int) ([]*model.TeamTopCreator, error) {
	ret := _m.Called(ctx, userID, since, limit)

	if len(ret) == 0 {
		panic("no return value specified for TopCreatorsByTeam")
	}

	var r0 []*model.TeamTopCreator
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, int) ([]*model.TeamTopCreator, error)); ok {
		return rf(ctx, userID, since, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, int) []*model.TeamTopCreator); ok {
		r0 = rf(ctx, userID, since, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.TeamTopCreator)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, int) error); ok {
		r1 = rf(ctx, userID, since, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskReportService_TopCreatorsByTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TopCreatorsByTeam'
type TaskReportService_TopCreatorsByTeam_Call struct {
	*mock.Call
}

// TopCreatorsByTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - since time.Time
//   - limit int
func (_e *TaskReportService_Expecter) TopCreatorsByTeam(ctx interface{}, userID interface{}, since interface{}, limit interface{}) *TaskReportService_TopCreatorsByTeam_Call {
	return &TaskReportService_TopCreatorsByTeam_Call{Call: _e.mock.On("TopCreatorsByTeam", ctx, userID, since, limit)}
}

func (_c *TaskReportService_TopCreatorsByTeam_Call) Run(run func(ctx context.Context, userID uuid.UUID, since time.Time, limit int)) *TaskReportService_TopCreatorsByTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time), args[3].(int))
	})
	return _c
}

func (_c *TaskReportService_TopCreatorsByTeam_Call) Return(_a0 []*model.TeamTopCreator, _a1 error) *TaskReportService_TopCreatorsByTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskReportService_TopCreatorsByTeam_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time, int) ([]*model.TeamTopCreator, error)) *TaskReportService_TopCreatorsByTeam_Call {
	_c.Call.Return(run)
	return _c
}

// NewTaskReportService creates a new instance of TaskReportService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskReportService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskReportService {
	mock := &TaskReportService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
