// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/workspace/task/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// TaskService is an autogenerated mock type for the TaskService type
type TaskService struct {
	mock.Mock
}

type TaskService_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskService) EXPECT() *TaskService_Expecter {
	return &TaskService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, userID, teamID, input
func (_m *TaskService) Create(ctx context.Context, userID uuid.UUID, teamID uuid.UUID, input *model.TaskInput) (*model.Task, error) {
	ret := _m.Called(ctx, userID, teamID, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *model.TaskInput) (*model.Task, error)); ok {
		return rf(ctx, userID, teamID, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *model.TaskInput) *model.Task); ok {
		r0 = rf(ctx, userID, teamID, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, *model.TaskInput) error); ok {
		r1 = rf(ctx, userID, teamID, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TaskService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - teamID uuid.UUID
//   - input *model.TaskInput
func (_e *TaskService_Expecter) Create(ctx interface{}, userID interface{}, teamID interface{}, input interface{}) *TaskService_Create_Call {
	return &TaskService_Create_Call{Call: _e.mock.On("Create", ctx, userID, teamID, input)}
}

func (_c *TaskService_Create_Call) Run(run func(ctx context.Context, userID uuid.UUID, teamID uuid.UUID, input *model.TaskInput)) *TaskService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(*model.TaskInput))
	})
	return _c
}

func (_c *TaskService_Create_Call) Return(_a0 *model.Task, _a1 error) *TaskService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskService_Create_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, *model.TaskInput) (*model.Task, error)) *TaskService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID, taskID
func (_m *TaskService) Delete(ctx context.Context, userID uuid.UUID, taskID uuid.UUID) error {
	ret := _m.Called(ctx, userID, taskID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, taskID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TaskService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TaskService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - taskID uuid.UUID
func (_e *TaskService_Expecter) Delete(ctx interface{}, userID interface{}, taskID interface{}) *TaskService_Delete_Call {
	return &TaskService_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, taskID)}
}

func (_c *TaskService_Delete_Call) Run(run func(ctx context.Context, userID uuid.UUID, taskID uuid.UUID)) *TaskService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TaskService_Delete_Call) Return(_a0 error) *TaskService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TaskService_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *TaskService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, taskID, userID
func (_m *TaskService) GetByID(ctx context.Context, taskID uuid.UUID, userID uuid.UUID) (*model.Task, error) {
	ret := _m.Called(ctx, taskID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.Task, error)); ok {
		return rf(ctx, taskID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.Task); ok {
		r0 = rf(ctx, taskID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, taskID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type TaskService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID uuid.UUID
//   - userID uuid.UUID
func (_e *TaskService_Expecter) GetByID(ctx interface{}, taskID interface{}, userID interface{}) *TaskService_GetByID_Call {
	return &TaskService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, taskID, userID)}
}

func (_c *TaskService_GetByID_Call) Run(run func(ctx context.Context, taskID uuid.UUID, userID uuid.UUID)) *TaskService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TaskService_GetByID_Call) Return(_a0 *model.Task, _a1 error) *TaskService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskService_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*model.Task, error)) *TaskService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetHistory provides a mock function with given fields: ctx, taskID, userID
func (_m *TaskService) GetHistory(ctx context.Context, taskID uuid.UUID, userID uuid.UUID) ([]*model.TaskHistory, error) {
	ret := _m.Called(ctx, taskID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetHistory")
	}

	var r0 []*model.TaskHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]*model.TaskHistory, error)); ok {
		return rf(ctx, taskID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []*model.TaskHistory); ok {
		r0 = rf(ctx, taskID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.TaskHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, taskID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskService_GetHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHistory'
type TaskService_GetHistory_Call struct {
	*mock.Call
}

// GetHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID uuid.UUID
//   - userID uuid.UUID
func (_e *TaskService_Expecter) GetHistory(ctx interface{}, taskID interface{}, userID interface{}) *TaskService_GetHistory_Call {
	return &TaskService_GetHistory_Call{Call: _e.mock.On("GetHistory", ctx, taskID, userID)}
}

func (_c *TaskService_GetHistory_Call) Run(run func(ctx context.Context, taskID uuid.UUID, userID uuid.UUID)) *TaskService_GetHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TaskService_GetHistory_Call) Return(_a0 []*model.TaskHistory, _a1 error) *TaskService_GetHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskService_GetHistory_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) ([]*model.TaskHistory, error)) *TaskService_GetHistory_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, userID, filter
func (_m *TaskService) List(ctx context.Context, userID uuid.UUID, filter *model.TaskListFilter) ([]*model.Task, int, error) {
	ret := _m.Called(ctx, userID, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.Task
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.TaskListFilter) ([]*model.Task, int, error)); ok {
		return rf(ctx, userID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.TaskListFilter) []*model.Task); ok {
		r0 = rf(ctx, userID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *model.TaskListFilter) int); ok {
		r1 = rf(ctx, userID, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, *model.TaskListFilter) error); ok {
		r2 = rf(ctx, userID, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// TaskService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type TaskService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - filter *model.TaskListFilter
func (_e *TaskService_Expecter) List(ctx interface{}, userID interface{}, filter interface{}) *TaskService_List_Call {
	return &TaskService_List_Call{Call: _e.mock.On("List", ctx, userID, filter)}
}

func (_c *TaskService_List_Call) Run(run func(ctx context.Context, userID uuid.UUID, filter *model.TaskListFilter)) *TaskService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*model.TaskListFilter))
	})
	return _c
}

func (_c *TaskService_List_Call) Return(_a0 []*model.Task, _a1 int, _a2 error) *TaskService_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *TaskService_List_Call) RunAndReturn(run func(context.Context, uuid.UUID, *model.TaskListFilter) ([]*model.Task, int, error)) *TaskService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Restore provides a mock function with given fields: ctx, userID, taskID
func (_m *TaskService) Restore(ctx context.Context, userID uuid.UUID, taskID uuid.UUID) (*model.Task, error) {
	ret := _m.Called(ctx, userID, taskID)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 *model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.Task, error)); ok {
		return rf(ctx, userID, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.Task); ok {
		r0 = rf(ctx, userID, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, userID, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskService_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type TaskService_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - taskID uuid.UUID
func (_e *TaskService_Expecter) Restore(ctx interface{}, userID interface{}, taskID interface{}) *TaskService_Restore_Call {
	return &TaskService_Restore_Call{Call: _e.mock.On("Restore", ctx, userID, taskID)}
}

func (_c *TaskService_Restore_Call) Run(run func(ctx context.Context, userID uuid.UUID, taskID uuid.UUID)) *TaskService_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TaskService_Restore_Call) Return(_a0 *model.Task, _a1 error) *TaskService_Restore_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskService_Restore_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*model.Task, error)) *TaskService_Restore_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, userID, taskID, input
func (_m *TaskService) Update(ctx context.Context, userID uuid.UUID, taskID uuid.UUID, input *model.TaskInput) (*model.Task, error) {
	ret := _m.Called(ctx, userID, taskID, input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *model.TaskInput) (*model.Task, error)); ok {
		return rf(ctx, userID, taskID, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *model.TaskInput) *model.Task); ok {
		r0 = rf(ctx, userID, taskID, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, *model.TaskInput) error); ok {
		r1 = rf(ctx, userID, taskID, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type TaskService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - taskID uuid.UUID
//   - input *model.TaskInput
func (_e *TaskService_Expecter) Update(ctx interface{}, userID interface{}, taskID interface{}, input interface{}) *TaskService_Update_Call {
	return &TaskService_Update_Call{Call: _e.mock.On("Update", ctx, userID, taskID, input)}
}

func (_c *TaskService_Update_Call) Run(run func(ctx context.Context, userID uuid.UUID, taskID uuid.UUID, input *model.TaskInput)) *TaskService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(*model.TaskInput))
	})
	return _c
}

func (_c *TaskService_Update_Call) Return(_a0 *model.Task, _a1 error) *TaskService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskService_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, *model.TaskInput) (*model.Task, error)) *TaskService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewTaskService creates a new instance of TaskService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskService {
	mock := &TaskService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
