// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model2 "github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/workspace/team/model"
	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"
)

// TeamReaderRepository is an autogenerated mock type for the TeamReaderRepository type
type TeamReaderRepository struct {
	mock.Mock
}

type TeamReaderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TeamReaderRepository) EXPECT() *TeamReaderRepository_Expecter {
	return &TeamReaderRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, tx, teamID
func (_m *TeamReaderRepository) GetByID(ctx context.Context, tx *sqlx.Tx, teamID string) (*model2.Team, error) {
	ret := _m.Called(ctx, tx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model2.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, string) (*model2.Team, error)); ok {
		return rf(ctx, tx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, string) *model2.Team); ok {
		r0 = rf(ctx, tx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model2.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, string) error); ok {
		r1 = rf(ctx, tx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamReaderRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type TeamReaderRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - teamID string
func (_e *TeamReaderRepository_Expecter) GetByID(ctx interface{}, tx interface{}, teamID interface{}) *TeamReaderRepository_GetByID_Call {
	return &TeamReaderRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, tx, teamID)}
}

func (_c *TeamReaderRepository_GetByID_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, teamID string)) *TeamReaderRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(string))
	})
	return _c
}

func (_c *TeamReaderRepository_GetByID_Call) Return(_a0 *model2.Team, _a1 error) *TeamReaderRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamReaderRepository_GetByID_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, string) (*model2.Team, error)) *TeamReaderRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function with given fields: ctx, tx, userID
func (_m *TeamReaderRepository) ListByUserID(ctx context.Context, tx *sqlx.Tx, userID string) ([]*model2.TeamWithRole, error) {
	ret := _m.Called(ctx, tx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []*model2.TeamWithRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, string) ([]*model2.TeamWithRole, error)); ok {
		return rf(ctx, tx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, string) []*model2.TeamWithRole); ok {
		r0 = rf(ctx, tx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model2.TeamWithRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, string) error); ok {
		r1 = rf(ctx, tx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamReaderRepository_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type TeamReaderRepository_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - userID string
func (_e *TeamReaderRepository_Expecter) ListByUserID(ctx interface{}, tx interface{}, userID interface{}) *TeamReaderRepository_ListByUserID_Call {
	return &TeamReaderRepository_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, tx, userID)}
}

func (_c *TeamReaderRepository_ListByUserID_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, userID string)) *TeamReaderRepository_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(string))
	})
	return _c
}

func (_c *TeamReaderRepository_ListByUserID_Call) Return(_a0 []*model2.TeamWithRole, _a1 error) *TeamReaderRepository_ListByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamReaderRepository_ListByUserID_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, string) ([]*model2.TeamWithRole, error)) *TeamReaderRepository_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewTeamReaderRepository creates a new instance of TeamReaderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamReaderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamReaderRepository {
	mock := &TeamReaderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
