// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model2 "github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/workspace/team/model"
	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"
)

// TeamWriterRepository is an autogenerated mock type for the TeamWriterRepository type
type TeamWriterRepository struct {
	mock.Mock
}

type TeamWriterRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TeamWriterRepository) EXPECT() *TeamWriterRepository_Expecter {
	return &TeamWriterRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, tx, input, createdBy
func (_m *TeamWriterRepository) Create(ctx context.Context, tx *sqlx.Tx, input *model2.TeamInput, createdBy string) (*model2.Team, error) {
	ret := _m.Called(ctx, tx, input, createdBy)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model2.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *model2.TeamInput, string) (*model2.Team, error)); ok {
		return rf(ctx, tx, input, createdBy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *model2.TeamInput, string) *model2.Team); ok {
		r0 = rf(ctx, tx, input, createdBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model2.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, *model2.TeamInput, string) error); ok {
		r1 = rf(ctx, tx, input, createdBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamWriterRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TeamWriterRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - input *model.TeamInput
//   - createdBy string
func (_e *TeamWriterRepository_Expecter) Create(ctx interface{}, tx interface{}, input interface{}, createdBy interface{}) *TeamWriterRepository_Create_Call {
	return &TeamWriterRepository_Create_Call{Call: _e.mock.On("Create", ctx, tx, input, createdBy)}
}

func (_c *TeamWriterRepository_Create_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, input *model2.TeamInput, createdBy string)) *TeamWriterRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(*model2.TeamInput), args[3].(string))
	})
	return _c
}

func (_c *TeamWriterRepository_Create_Call) Return(_a0 *model2.Team, _a1 error) *TeamWriterRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamWriterRepository_Create_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, *model2.TeamInput, string) (*model2.Team, error)) *TeamWriterRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewTeamWriterRepository creates a new instance of TeamWriterRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamWriterRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamWriterRepository {
	mock := &TeamWriterRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
