// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/team/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// TeamService is an autogenerated mock type for the TeamService type
type TeamService struct {
	mock.Mock
}

type TeamService_Expecter struct {
	mock *mock.Mock
}

func (_m *TeamService) EXPECT() *TeamService_Expecter {
	return &TeamService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, input, ownerUserID
func (_m *TeamService) Create(ctx context.Context, input *model.TeamInput, ownerUserID uuid.UUID) (*model.Team, error) {
	ret := _m.Called(ctx, input, ownerUserID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.TeamInput, uuid.UUID) (*model.Team, error)); ok {
		return rf(ctx, input, ownerUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.TeamInput, uuid.UUID) *model.Team); ok {
		r0 = rf(ctx, input, ownerUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.TeamInput, uuid.UUID) error); ok {
		r1 = rf(ctx, input, ownerUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TeamService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - input *model.TeamInput
//   - ownerUserID uuid.UUID
func (_e *TeamService_Expecter) Create(ctx interface{}, input interface{}, ownerUserID interface{}) *TeamService_Create_Call {
	return &TeamService_Create_Call{Call: _e.mock.On("Create", ctx, input, ownerUserID)}
}

func (_c *TeamService_Create_Call) Run(run func(ctx context.Context, input *model.TeamInput, ownerUserID uuid.UUID)) *TeamService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.TeamInput), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TeamService_Create_Call) Return(_a0 *model.Team, _a1 error) *TeamService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamService_Create_Call) RunAndReturn(run func(context.Context, *model.TeamInput, uuid.UUID) (*model.Team, error)) *TeamService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, teamID
func (_m *TeamService) GetByID(ctx context.Context, teamID uuid.UUID) (*model.TeamWithMembers, error) {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.TeamWithMembers
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.TeamWithMembers, error)); ok {
		return rf(ctx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.TeamWithMembers); ok {
		r0 = rf(ctx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TeamWithMembers)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type TeamService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
func (_e *TeamService_Expecter) GetByID(ctx interface{}, teamID interface{}) *TeamService_GetByID_Call {
	return &TeamService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, teamID)}
}

func (_c *TeamService_GetByID_Call) Run(run func(ctx context.Context, teamID uuid.UUID)) *TeamService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *TeamService_GetByID_Call) Return(_a0 *model.TeamWithMembers, _a1 error) *TeamService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamService_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.TeamWithMembers, error)) *TeamService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMember provides a mock function with given fields: ctx, teamID, userID
func (_m *TeamService) GetMember(ctx context.Context, teamID uuid.UUID, userID uuid.UUID) (*model.TeamMember, error) {
	ret := _m.Called(ctx, teamID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMember")
	}

	var r0 *model.TeamMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.TeamMember, error)); ok {
		return rf(ctx, teamID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.TeamMember); ok {
		r0 = rf(ctx, teamID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TeamMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, teamID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamService_GetMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMember'
type TeamService_GetMember_Call struct {
	*mock.Call
}

// GetMember is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
//   - userID uuid.UUID
func (_e *TeamService_Expecter) GetMember(ctx interface{}, teamID interface{}, userID interface{}) *TeamService_GetMember_Call {
	return &TeamService_GetMember_Call{Call: _e.mock.On("GetMember", ctx, teamID, userID)}
}

func (_c *TeamService_GetMember_Call) Run(run func(ctx context.Context, teamID uuid.UUID, userID uuid.UUID)) *TeamService_GetMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TeamService_GetMember_Call) Return(_a0 *model.TeamMember, _a1 error) *TeamService_GetMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamService_GetMember_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*model.TeamMember, error)) *TeamService_GetMember_Call {
	_c.Call.Return(run)
	return _c
}

// InviteByEmail provides a mock function with given fields: ctx, teamID, inviterUserID, inviteeEmail, role
func (_m *TeamService) InviteByEmail(ctx context.Context, teamID uuid.UUID, inviterUserID uuid.UUID, inviteeEmail string, role string) (*model.TeamInvitation, error) {
	ret := _m.Called(ctx, teamID, inviterUserID, inviteeEmail, role)

	if len(ret) == 0 {
		panic("no return value specified for InviteByEmail")
	}

	var r0 *model.TeamInvitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string) (*model.TeamInvitation, error)); ok {
		return rf(ctx, teamID, inviterUserID, inviteeEmail, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string) *model.TeamInvitation); ok {
		r0 = rf(ctx, teamID, inviterUserID, inviteeEmail, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TeamInvitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, teamID, inviterUserID, inviteeEmail, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamService_InviteByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InviteByEmail'
type TeamService_InviteByEmail_Call struct {
	*mock.Call
}

// InviteByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
//   - inviterUserID uuid.UUID
//   - inviteeEmail string
//   - role string
func (_e *TeamService_Expecter) InviteByEmail(ctx interface{}, teamID interface{}, inviterUserID interface{}, inviteeEmail interface{}, role interface{}) *TeamService_InviteByEmail_Call {
	return &TeamService_InviteByEmail_Call{Call: _e.mock.On("InviteByEmail", ctx, teamID, inviterUserID, inviteeEmail, role)}
}

func (_c *TeamService_InviteByEmail_Call) Run(run func(ctx context.Context, teamID uuid.UUID, inviterUserID uuid.UUID, inviteeEmail string, role string)) *TeamService_InviteByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *TeamService_InviteByEmail_Call) Return(_a0 *model.TeamInvitation, _a1 error) *TeamService_InviteByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamService_InviteByEmail_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string, string) (*model.TeamInvitation, error)) *TeamService_InviteByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function with given fields: ctx, userID
func (_m *TeamService) ListByUserID(ctx context.Context, userID uuid.UUID) ([]*model.TeamWithRole, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []*model.TeamWithRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.TeamWithRole, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.TeamWithRole); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.TeamWithRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamService_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type TeamService_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *TeamService_Expecter) ListByUserID(ctx interface{}, userID interface{}) *TeamService_ListByUserID_Call {
	return &TeamService_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userID)}
}

func (_c *TeamService_ListByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *TeamService_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *TeamService_ListByUserID_Call) Return(_a0 []*model.TeamWithRole, _a1 error) *TeamService_ListByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamService_ListByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*model.TeamWithRole, error)) *TeamService_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewTeamService creates a new instance of TeamService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamService {
	mock := &TeamService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
