// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/identity/user/model"
	mock "github.com/stretchr/testify/mock"
)

// UserCacheRepository is an autogenerated mock type for the UserCacheRepository type
type UserCacheRepository struct {
	mock.Mock
}

type UserCacheRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserCacheRepository) EXPECT() *UserCacheRepository_Expecter {
	return &UserCacheRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, id
func (_m *UserCacheRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserCacheRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type UserCacheRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *UserCacheRepository_Expecter) Delete(ctx interface{}, id interface{}) *UserCacheRepository_Delete_Call {
	return &UserCacheRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *UserCacheRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *UserCacheRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserCacheRepository_Delete_Call) Return(_a0 error) *UserCacheRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserCacheRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *UserCacheRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *UserCacheRepository) Get(ctx context.Context, id string) (*model.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserCacheRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type UserCacheRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *UserCacheRepository_Expecter) Get(ctx interface{}, id interface{}) *UserCacheRepository_Get_Call {
	return &UserCacheRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *UserCacheRepository_Get_Call) Run(run func(ctx context.Context, id string)) *UserCacheRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserCacheRepository_Get_Call) Return(_a0 *model.User, _a1 error) *UserCacheRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserCacheRepository_Get_Call) RunAndReturn(run func(context.Context, string) (*model.User, error)) *UserCacheRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, id, user
func (_m *UserCacheRepository) Set(ctx context.Context, id string, user *model.User) error {
	ret := _m.Called(ctx, id, user)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.User) error); ok {
		r0 = rf(ctx, id, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserCacheRepository_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type UserCacheRepository_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - user *model.User
func (_e *UserCacheRepository_Expecter) Set(ctx interface{}, id interface{}, user interface{}) *UserCacheRepository_Set_Call {
	return &UserCacheRepository_Set_Call{Call: _e.mock.On("Set", ctx, id, user)}
}

func (_c *UserCacheRepository_Set_Call) Run(run func(ctx context.Context, id string, user *model.User)) *UserCacheRepository_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*model.User))
	})
	return _c
}

func (_c *UserCacheRepository_Set_Call) Return(_a0 error) *UserCacheRepository_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserCacheRepository_Set_Call) RunAndReturn(run func(context.Context, string, *model.User) error) *UserCacheRepository_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserCacheRepository creates a new instance of UserCacheRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserCacheRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserCacheRepository {
	mock := &UserCacheRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
