// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	"github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/workspace/team/model"
	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"
)

// InvitationWriterRepository is an autogenerated mock type for the InvitationWriterRepository type
type InvitationWriterRepository struct {
	mock.Mock
}

type InvitationWriterRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *InvitationWriterRepository) EXPECT() *InvitationWriterRepository_Expecter {
	return &InvitationWriterRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, tx, inv
func (_m *InvitationWriterRepository) Create(ctx context.Context, tx *sqlx.Tx, inv *model.TeamInvitation) error {
	ret := _m.Called(ctx, tx, inv)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *model.TeamInvitation) error); ok {
		r0 = rf(ctx, tx, inv)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InvitationWriterRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type InvitationWriterRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - inv *model.TeamInvitation
func (_e *InvitationWriterRepository_Expecter) Create(ctx interface{}, tx interface{}, inv interface{}) *InvitationWriterRepository_Create_Call {
	return &InvitationWriterRepository_Create_Call{Call: _e.mock.On("Create", ctx, tx, inv)}
}

func (_c *InvitationWriterRepository_Create_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, inv *model.TeamInvitation)) *InvitationWriterRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(*model.TeamInvitation))
	})
	return _c
}

func (_c *InvitationWriterRepository_Create_Call) Return(_a0 error) *InvitationWriterRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InvitationWriterRepository_Create_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, *model.TeamInvitation) error) *InvitationWriterRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewInvitationWriterRepository creates a new instance of InvitationWriterRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInvitationWriterRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InvitationWriterRepository {
	mock := &InvitationWriterRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
