// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/identity/account/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AccountService is an autogenerated mock type for the AccountService type
type AccountService struct {
	mock.Mock
}

type AccountService_Expecter struct {
	mock *mock.Mock
}

func (_m *AccountService) EXPECT() *AccountService_Expecter {
	return &AccountService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, input
func (_m *AccountService) Login(ctx context.Context, input model.LoginInput) (string, string, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, model.LoginInput) (string, string, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.LoginInput) string); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.LoginInput) string); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, model.LoginInput) error); ok {
		r2 = rf(ctx, input)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// AccountService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type AccountService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - input model.LoginInput
func (_e *AccountService_Expecter) Login(ctx interface{}, input interface{}) *AccountService_Login_Call {
	return &AccountService_Login_Call{Call: _e.mock.On("Login", ctx, input)}
}

func (_c *AccountService_Login_Call) Run(run func(ctx context.Context, input model.LoginInput)) *AccountService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.LoginInput))
	})
	return _c
}

func (_c *AccountService_Login_Call) Return(accessToken string, refreshToken string, err error) *AccountService_Login_Call {
	_c.Call.Return(accessToken, refreshToken, err)
	return _c
}

func (_c *AccountService_Login_Call) RunAndReturn(run func(context.Context, model.LoginInput) (string, string, error)) *AccountService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, refreshToken
func (_m *AccountService) Logout(ctx context.Context, refreshToken string) error {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AccountService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type AccountService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *AccountService_Expecter) Logout(ctx interface{}, refreshToken interface{}) *AccountService_Logout_Call {
	return &AccountService_Logout_Call{Call: _e.mock.On("Logout", ctx, refreshToken)}
}

func (_c *AccountService_Logout_Call) Run(run func(ctx context.Context, refreshToken string)) *AccountService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AccountService_Logout_Call) Return(_a0 error) *AccountService_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AccountService_Logout_Call) RunAndReturn(run func(context.Context, string) error) *AccountService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function with given fields: ctx, refreshToken, userAgent, ip
func (_m *AccountService) Refresh(ctx context.Context, refreshToken string, userAgent string, ip string) (string, uuid.UUID, error) {
	ret := _m.Called(ctx, refreshToken, userAgent, ip)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 string
	var r1 uuid.UUID
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (string, uuid.UUID, error)); ok {
		return rf(ctx, refreshToken, userAgent, ip)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, refreshToken, userAgent, ip)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) uuid.UUID); ok {
		r1 = rf(ctx, refreshToken, userAgent, ip)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string) error); ok {
		r2 = rf(ctx, refreshToken, userAgent, ip)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// AccountService_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type AccountService_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
//   - userAgent string
//   - ip string
func (_e *AccountService_Expecter) Refresh(ctx interface{}, refreshToken interface{}, userAgent interface{}, ip interface{}) *AccountService_Refresh_Call {
	return &AccountService_Refresh_Call{Call: _e.mock.On("Refresh", ctx, refreshToken, userAgent, ip)}
}

func (_c *AccountService_Refresh_Call) Run(run func(ctx context.Context, refreshToken string, userAgent string, ip string)) *AccountService_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *AccountService_Refresh_Call) Return(accessToken string, userID uuid.UUID, err error) *AccountService_Refresh_Call {
	_c.Call.Return(accessToken, userID, err)
	return _c
}

func (_c *AccountService_Refresh_Call) RunAndReturn(run func(context.Context, string, string, string) (string, uuid.UUID, error)) *AccountService_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, input
func (_m *AccountService) Register(ctx context.Context, input model.RegisterInput) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.RegisterInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AccountService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type AccountService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - input model.RegisterInput
func (_e *AccountService_Expecter) Register(ctx interface{}, input interface{}) *AccountService_Register_Call {
	return &AccountService_Register_Call{Call: _e.mock.On("Register", ctx, input)}
}

func (_c *AccountService_Register_Call) Run(run func(ctx context.Context, input model.RegisterInput)) *AccountService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.RegisterInput))
	})
	return _c
}

func (_c *AccountService_Register_Call) Return(_a0 error) *AccountService_Register_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AccountService_Register_Call) RunAndReturn(run func(context.Context, model.RegisterInput) error) *AccountService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewAccountService creates a new instance of AccountService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountService {
	mock := &AccountService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
