// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AccountService is an autogenerated mock type for the AccountService type
type AccountService struct {
	mock.Mock
}

type AccountService_Expecter struct {
	mock *mock.Mock
}

func (_m *AccountService) EXPECT() *AccountService_Expecter {
	return &AccountService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, email, password, userAgent, ip
func (_m *AccountService) Login(ctx context.Context, email string, password string, userAgent string, ip string) (uuid.UUID, error) {
	ret := _m.Called(ctx, email, password, userAgent, ip)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (uuid.UUID, error)); ok {
		return rf(ctx, email, password, userAgent, ip)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) uuid.UUID); ok {
		r0 = rf(ctx, email, password, userAgent, ip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, email, password, userAgent, ip)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type AccountService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
//   - userAgent string
//   - ip string
func (_e *AccountService_Expecter) Login(ctx interface{}, email interface{}, password interface{}, userAgent interface{}, ip interface{}) *AccountService_Login_Call {
	return &AccountService_Login_Call{Call: _e.mock.On("Login", ctx, email, password, userAgent, ip)}
}

func (_c *AccountService_Login_Call) Run(run func(ctx context.Context, email string, password string, userAgent string, ip string)) *AccountService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *AccountService_Login_Call) Return(sessionID uuid.UUID, err error) *AccountService_Login_Call {
	_c.Call.Return(sessionID, err)
	return _c
}

func (_c *AccountService_Login_Call) RunAndReturn(run func(context.Context, string, string, string, string) (uuid.UUID, error)) *AccountService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, sessionID
func (_m *AccountService) Logout(ctx context.Context, sessionID uuid.UUID) error {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AccountService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type AccountService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
func (_e *AccountService_Expecter) Logout(ctx interface{}, sessionID interface{}) *AccountService_Logout_Call {
	return &AccountService_Logout_Call{Call: _e.mock.On("Logout", ctx, sessionID)}
}

func (_c *AccountService_Logout_Call) Run(run func(ctx context.Context, sessionID uuid.UUID)) *AccountService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AccountService_Logout_Call) Return(_a0 error) *AccountService_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AccountService_Logout_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *AccountService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, email, password, name
func (_m *AccountService) Register(ctx context.Context, email string, password string, name string) error {
	ret := _m.Called(ctx, email, password, name)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, email, password, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AccountService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type AccountService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
//   - name string
func (_e *AccountService_Expecter) Register(ctx interface{}, email interface{}, password interface{}, name interface{}) *AccountService_Register_Call {
	return &AccountService_Register_Call{Call: _e.mock.On("Register", ctx, email, password, name)}
}

func (_c *AccountService_Register_Call) Run(run func(ctx context.Context, email string, password string, name string)) *AccountService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *AccountService_Register_Call) Return(_a0 error) *AccountService_Register_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AccountService_Register_Call) RunAndReturn(run func(context.Context, string, string, string) error) *AccountService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// Whoami provides a mock function with given fields: ctx, sessionID
func (_m *AccountService) Whoami(ctx context.Context, sessionID uuid.UUID) (uuid.UUID, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Whoami")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (uuid.UUID, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) uuid.UUID); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountService_Whoami_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Whoami'
type AccountService_Whoami_Call struct {
	*mock.Call
}

// Whoami is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
func (_e *AccountService_Expecter) Whoami(ctx interface{}, sessionID interface{}) *AccountService_Whoami_Call {
	return &AccountService_Whoami_Call{Call: _e.mock.On("Whoami", ctx, sessionID)}
}

func (_c *AccountService_Whoami_Call) Run(run func(ctx context.Context, sessionID uuid.UUID)) *AccountService_Whoami_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AccountService_Whoami_Call) Return(userID uuid.UUID, err error) *AccountService_Whoami_Call {
	_c.Call.Return(userID, err)
	return _c
}

func (_c *AccountService_Whoami_Call) RunAndReturn(run func(context.Context, uuid.UUID) (uuid.UUID, error)) *AccountService_Whoami_Call {
	_c.Call.Return(run)
	return _c
}

// NewAccountService creates a new instance of AccountService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountService {
	mock := &AccountService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
