// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/workspace/task/model"
	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"

	uuid "github.com/google/uuid"
)

// TaskCommentWriterRepository is an autogenerated mock type for the TaskCommentWriterRepository type
type TaskCommentWriterRepository struct {
	mock.Mock
}

type TaskCommentWriterRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskCommentWriterRepository) EXPECT() *TaskCommentWriterRepository_Expecter {
	return &TaskCommentWriterRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, tx, taskID, userID, content
func (_m *TaskCommentWriterRepository) Create(ctx context.Context, tx *sqlx.Tx, taskID uuid.UUID, userID uuid.UUID, content string) (model.TaskComment, error) {
	ret := _m.Called(ctx, tx, taskID, userID, content)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.TaskComment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID, string) (model.TaskComment, error)); ok {
		return rf(ctx, tx, taskID, userID, content)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID, string) model.TaskComment); ok {
		r0 = rf(ctx, tx, taskID, userID, content)
	} else {
		r0 = ret.Get(0).(model.TaskComment)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = rf(ctx, tx, taskID, userID, content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskCommentWriterRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TaskCommentWriterRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - taskID uuid.UUID
//   - userID uuid.UUID
//   - content string
func (_e *TaskCommentWriterRepository_Expecter) Create(ctx interface{}, tx interface{}, taskID interface{}, userID interface{}, content interface{}) *TaskCommentWriterRepository_Create_Call {
	return &TaskCommentWriterRepository_Create_Call{Call: _e.mock.On("Create", ctx, tx, taskID, userID, content)}
}

func (_c *TaskCommentWriterRepository_Create_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, taskID uuid.UUID, userID uuid.UUID, content string)) *TaskCommentWriterRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID), args[3].(uuid.UUID), args[4].(string))
	})
	return _c
}

func (_c *TaskCommentWriterRepository_Create_Call) Return(_a0 model.TaskComment, _a1 error) *TaskCommentWriterRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskCommentWriterRepository_Create_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID, string) (model.TaskComment, error)) *TaskCommentWriterRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewTaskCommentWriterRepository creates a new instance of TaskCommentWriterRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskCommentWriterRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskCommentWriterRepository {
	mock := &TaskCommentWriterRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
