// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/workspace/task/model"
	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"

	uuid "github.com/google/uuid"
)

// TaskCommentReaderRepository is an autogenerated mock type for the TaskCommentReaderRepository type
type TaskCommentReaderRepository struct {
	mock.Mock
}

type TaskCommentReaderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskCommentReaderRepository) EXPECT() *TaskCommentReaderRepository_Expecter {
	return &TaskCommentReaderRepository_Expecter{mock: &_m.Mock}
}

// ListByTaskID provides a mock function with given fields: ctx, tx, taskID
func (_m *TaskCommentReaderRepository) ListByTaskID(ctx context.Context, tx *sqlx.Tx, taskID uuid.UUID) ([]model.TaskComment, error) {
	ret := _m.Called(ctx, tx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for ListByTaskID")
	}

	var r0 []model.TaskComment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID) ([]model.TaskComment, error)); ok {
		return rf(ctx, tx, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID) []model.TaskComment); ok {
		r0 = rf(ctx, tx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.TaskComment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskCommentReaderRepository_ListByTaskID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByTaskID'
type TaskCommentReaderRepository_ListByTaskID_Call struct {
	*mock.Call
}

// ListByTaskID is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - taskID uuid.UUID
func (_e *TaskCommentReaderRepository_Expecter) ListByTaskID(ctx interface{}, tx interface{}, taskID interface{}) *TaskCommentReaderRepository_ListByTaskID_Call {
	return &TaskCommentReaderRepository_ListByTaskID_Call{Call: _e.mock.On("ListByTaskID", ctx, tx, taskID)}
}

func (_c *TaskCommentReaderRepository_ListByTaskID_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, taskID uuid.UUID)) *TaskCommentReaderRepository_ListByTaskID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TaskCommentReaderRepository_ListByTaskID_Call) Return(_a0 []model.TaskComment, _a1 error) *TaskCommentReaderRepository_ListByTaskID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskCommentReaderRepository_ListByTaskID_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID) ([]model.TaskComment, error)) *TaskCommentReaderRepository_ListByTaskID_Call {
	_c.Call.Return(run)
	return _c
}

// NewTaskCommentReaderRepository creates a new instance of TaskCommentReaderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskCommentReaderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskCommentReaderRepository {
	mock := &TaskCommentReaderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
