// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/workspace/task/model"
	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"

	uuid "github.com/google/uuid"
)

// TaskHistoryReaderRepository is an autogenerated mock type for the TaskHistoryReaderRepository type
type TaskHistoryReaderRepository struct {
	mock.Mock
}

type TaskHistoryReaderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskHistoryReaderRepository) EXPECT() *TaskHistoryReaderRepository_Expecter {
	return &TaskHistoryReaderRepository_Expecter{mock: &_m.Mock}
}

// ListByTaskID provides a mock function with given fields: ctx, tx, taskID
func (_m *TaskHistoryReaderRepository) ListByTaskID(ctx context.Context, tx *sqlx.Tx, taskID uuid.UUID) ([]model.TaskHistory, error) {
	ret := _m.Called(ctx, tx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for ListByTaskID")
	}

	var r0 []model.TaskHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID) ([]model.TaskHistory, error)); ok {
		return rf(ctx, tx, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID) []model.TaskHistory); ok {
		r0 = rf(ctx, tx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.TaskHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskHistoryReaderRepository_ListByTaskID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByTaskID'
type TaskHistoryReaderRepository_ListByTaskID_Call struct {
	*mock.Call
}

// ListByTaskID is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - taskID uuid.UUID
func (_e *TaskHistoryReaderRepository_Expecter) ListByTaskID(ctx interface{}, tx interface{}, taskID interface{}) *TaskHistoryReaderRepository_ListByTaskID_Call {
	return &TaskHistoryReaderRepository_ListByTaskID_Call{Call: _e.mock.On("ListByTaskID", ctx, tx, taskID)}
}

func (_c *TaskHistoryReaderRepository_ListByTaskID_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, taskID uuid.UUID)) *TaskHistoryReaderRepository_ListByTaskID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TaskHistoryReaderRepository_ListByTaskID_Call) Return(_a0 []model.TaskHistory, _a1 error) *TaskHistoryReaderRepository_ListByTaskID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskHistoryReaderRepository_ListByTaskID_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID) ([]model.TaskHistory, error)) *TaskHistoryReaderRepository_ListByTaskID_Call {
	_c.Call.Return(run)
	return _c
}

// NewTaskHistoryReaderRepository creates a new instance of TaskHistoryReaderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskHistoryReaderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskHistoryReaderRepository {
	mock := &TaskHistoryReaderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
