// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/workspace/task/model"
	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"
)

// TaskHistoryWriterRepository is an autogenerated mock type for the TaskHistoryWriterRepository type
type TaskHistoryWriterRepository struct {
	mock.Mock
}

type TaskHistoryWriterRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskHistoryWriterRepository) EXPECT() *TaskHistoryWriterRepository_Expecter {
	return &TaskHistoryWriterRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, tx, entry
func (_m *TaskHistoryWriterRepository) Create(ctx context.Context, tx *sqlx.Tx, entry model.TaskHistory) error {
	ret := _m.Called(ctx, tx, entry)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, model.TaskHistory) error); ok {
		r0 = rf(ctx, tx, entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TaskHistoryWriterRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TaskHistoryWriterRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - entry model.TaskHistory
func (_e *TaskHistoryWriterRepository_Expecter) Create(ctx interface{}, tx interface{}, entry interface{}) *TaskHistoryWriterRepository_Create_Call {
	return &TaskHistoryWriterRepository_Create_Call{Call: _e.mock.On("Create", ctx, tx, entry)}
}

func (_c *TaskHistoryWriterRepository_Create_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, entry model.TaskHistory)) *TaskHistoryWriterRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(model.TaskHistory))
	})
	return _c
}

func (_c *TaskHistoryWriterRepository_Create_Call) Return(_a0 error) *TaskHistoryWriterRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TaskHistoryWriterRepository_Create_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, model.TaskHistory) error) *TaskHistoryWriterRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewTaskHistoryWriterRepository creates a new instance of TaskHistoryWriterRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskHistoryWriterRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskHistoryWriterRepository {
	mock := &TaskHistoryWriterRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
