// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/workspace/task/model"
	mock "github.com/stretchr/testify/mock"

	resources "github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/workspace/task/repository/resources"

	time "time"

	uuid "github.com/google/uuid"
)

// TaskListCacheRepository is an autogenerated mock type for the TaskListCacheRepository type
type TaskListCacheRepository struct {
	mock.Mock
}

type TaskListCacheRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskListCacheRepository) EXPECT() *TaskListCacheRepository_Expecter {
	return &TaskListCacheRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, teamID, filter
func (_m *TaskListCacheRepository) Get(ctx context.Context, teamID uuid.UUID, filter *model.TaskListFilter) (*resources.TaskListPageCache, error) {
	ret := _m.Called(ctx, teamID, filter)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *resources.TaskListPageCache
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.TaskListFilter) (*resources.TaskListPageCache, error)); ok {
		return rf(ctx, teamID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.TaskListFilter) *resources.TaskListPageCache); ok {
		r0 = rf(ctx, teamID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*resources.TaskListPageCache)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *model.TaskListFilter) error); ok {
		r1 = rf(ctx, teamID, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskListCacheRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type TaskListCacheRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
//   - filter *model.TaskListFilter
func (_e *TaskListCacheRepository_Expecter) Get(ctx interface{}, teamID interface{}, filter interface{}) *TaskListCacheRepository_Get_Call {
	return &TaskListCacheRepository_Get_Call{Call: _e.mock.On("Get", ctx, teamID, filter)}
}

func (_c *TaskListCacheRepository_Get_Call) Run(run func(ctx context.Context, teamID uuid.UUID, filter *model.TaskListFilter)) *TaskListCacheRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*model.TaskListFilter))
	})
	return _c
}

func (_c *TaskListCacheRepository_Get_Call) Return(_a0 *resources.TaskListPageCache, _a1 error) *TaskListCacheRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskListCacheRepository_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID, *model.TaskListFilter) (*resources.TaskListPageCache, error)) *TaskListCacheRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidateByTeam provides a mock function with given fields: ctx, teamID
func (_m *TaskListCacheRepository) InvalidateByTeam(ctx context.Context, teamID uuid.UUID) error {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateByTeam")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, teamID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TaskListCacheRepository_InvalidateByTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateByTeam'
type TaskListCacheRepository_InvalidateByTeam_Call struct {
	*mock.Call
}

// InvalidateByTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
func (_e *TaskListCacheRepository_Expecter) InvalidateByTeam(ctx interface{}, teamID interface{}) *TaskListCacheRepository_InvalidateByTeam_Call {
	return &TaskListCacheRepository_InvalidateByTeam_Call{Call: _e.mock.On("InvalidateByTeam", ctx, teamID)}
}

func (_c *TaskListCacheRepository_InvalidateByTeam_Call) Run(run func(ctx context.Context, teamID uuid.UUID)) *TaskListCacheRepository_InvalidateByTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *TaskListCacheRepository_InvalidateByTeam_Call) Return(_a0 error) *TaskListCacheRepository_InvalidateByTeam_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TaskListCacheRepository_InvalidateByTeam_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *TaskListCacheRepository_InvalidateByTeam_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, teamID, filter, data, ttl
func (_m *TaskListCacheRepository) Set(ctx context.Context, teamID uuid.UUID, filter *model.TaskListFilter, data *resources.TaskListPageCache, ttl time.Duration) error {
	ret := _m.Called(ctx, teamID, filter, data, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.TaskListFilter, *resources.TaskListPageCache, time.Duration) error); ok {
		r0 = rf(ctx, teamID, filter, data, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TaskListCacheRepository_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type TaskListCacheRepository_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
//   - filter *model.TaskListFilter
//   - data *resources.TaskListPageCache
//   - ttl time.Duration
func (_e *TaskListCacheRepository_Expecter) Set(ctx interface{}, teamID interface{}, filter interface{}, data interface{}, ttl interface{}) *TaskListCacheRepository_Set_Call {
	return &TaskListCacheRepository_Set_Call{Call: _e.mock.On("Set", ctx, teamID, filter, data, ttl)}
}

func (_c *TaskListCacheRepository_Set_Call) Run(run func(ctx context.Context, teamID uuid.UUID, filter *model.TaskListFilter, data *resources.TaskListPageCache, ttl time.Duration)) *TaskListCacheRepository_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*model.TaskListFilter), args[3].(*resources.TaskListPageCache), args[4].(time.Duration))
	})
	return _c
}

func (_c *TaskListCacheRepository_Set_Call) Return(_a0 error) *TaskListCacheRepository_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TaskListCacheRepository_Set_Call) RunAndReturn(run func(context.Context, uuid.UUID, *model.TaskListFilter, *resources.TaskListPageCache, time.Duration) error) *TaskListCacheRepository_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewTaskListCacheRepository creates a new instance of TaskListCacheRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskListCacheRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskListCacheRepository {
	mock := &TaskListCacheRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
