// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/workspace/task/model"
	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"

	uuid "github.com/google/uuid"
)

// TaskCommentRepository is an autogenerated mock type for the TaskCommentRepository type
type TaskCommentRepository struct {
	mock.Mock
}

type TaskCommentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskCommentRepository) EXPECT() *TaskCommentRepository_Expecter {
	return &TaskCommentRepository_Expecter{mock: &_m.Mock}
}

// CreateComment provides a mock function with given fields: ctx, tx, taskID, userID, content
func (_m *TaskCommentRepository) CreateComment(ctx context.Context, tx *sqlx.Tx, taskID uuid.UUID, userID uuid.UUID, content string) (model.TaskComment, error) {
	ret := _m.Called(ctx, tx, taskID, userID, content)

	if len(ret) == 0 {
		panic("no return value specified for CreateComment")
	}

	var r0 model.TaskComment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID, string) (model.TaskComment, error)); ok {
		return rf(ctx, tx, taskID, userID, content)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID, string) model.TaskComment); ok {
		r0 = rf(ctx, tx, taskID, userID, content)
	} else {
		r0 = ret.Get(0).(model.TaskComment)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = rf(ctx, tx, taskID, userID, content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskCommentRepository_CreateComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateComment'
type TaskCommentRepository_CreateComment_Call struct {
	*mock.Call
}

// CreateComment is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - taskID uuid.UUID
//   - userID uuid.UUID
//   - content string
func (_e *TaskCommentRepository_Expecter) CreateComment(ctx interface{}, tx interface{}, taskID interface{}, userID interface{}, content interface{}) *TaskCommentRepository_CreateComment_Call {
	return &TaskCommentRepository_CreateComment_Call{Call: _e.mock.On("CreateComment", ctx, tx, taskID, userID, content)}
}

func (_c *TaskCommentRepository_CreateComment_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, taskID uuid.UUID, userID uuid.UUID, content string)) *TaskCommentRepository_CreateComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID), args[3].(uuid.UUID), args[4].(string))
	})
	return _c
}

func (_c *TaskCommentRepository_CreateComment_Call) Return(_a0 model.TaskComment, _a1 error) *TaskCommentRepository_CreateComment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskCommentRepository_CreateComment_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID, string) (model.TaskComment, error)) *TaskCommentRepository_CreateComment_Call {
	_c.Call.Return(run)
	return _c
}

// ListCommentsByTaskID provides a mock function with given fields: ctx, tx, taskID
func (_m *TaskCommentRepository) ListCommentsByTaskID(ctx context.Context, tx *sqlx.Tx, taskID uuid.UUID) ([]model.TaskComment, error) {
	ret := _m.Called(ctx, tx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for ListCommentsByTaskID")
	}

	var r0 []model.TaskComment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID) ([]model.TaskComment, error)); ok {
		return rf(ctx, tx, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID) []model.TaskComment); ok {
		r0 = rf(ctx, tx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.TaskComment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskCommentRepository_ListCommentsByTaskID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCommentsByTaskID'
type TaskCommentRepository_ListCommentsByTaskID_Call struct {
	*mock.Call
}

// ListCommentsByTaskID is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - taskID uuid.UUID
func (_e *TaskCommentRepository_Expecter) ListCommentsByTaskID(ctx interface{}, tx interface{}, taskID interface{}) *TaskCommentRepository_ListCommentsByTaskID_Call {
	return &TaskCommentRepository_ListCommentsByTaskID_Call{Call: _e.mock.On("ListCommentsByTaskID", ctx, tx, taskID)}
}

func (_c *TaskCommentRepository_ListCommentsByTaskID_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, taskID uuid.UUID)) *TaskCommentRepository_ListCommentsByTaskID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TaskCommentRepository_ListCommentsByTaskID_Call) Return(_a0 []model.TaskComment, _a1 error) *TaskCommentRepository_ListCommentsByTaskID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskCommentRepository_ListCommentsByTaskID_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID) ([]model.TaskComment, error)) *TaskCommentRepository_ListCommentsByTaskID_Call {
	_c.Call.Return(run)
	return _c
}

// NewTaskCommentRepository creates a new instance of TaskCommentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskCommentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskCommentRepository {
	mock := &TaskCommentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
