// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/workspace/task/model"
	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"

	uuid "github.com/google/uuid"
)

// TaskHistoryRepository is an autogenerated mock type for the TaskHistoryRepository type
type TaskHistoryRepository struct {
	mock.Mock
}

type TaskHistoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskHistoryRepository) EXPECT() *TaskHistoryRepository_Expecter {
	return &TaskHistoryRepository_Expecter{mock: &_m.Mock}
}

// CreateHistoryEntry provides a mock function with given fields: ctx, tx, entry
func (_m *TaskHistoryRepository) CreateHistoryEntry(ctx context.Context, tx *sqlx.Tx, entry *model.TaskHistory) error {
	ret := _m.Called(ctx, tx, entry)

	if len(ret) == 0 {
		panic("no return value specified for CreateHistoryEntry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *model.TaskHistory) error); ok {
		r0 = rf(ctx, tx, entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TaskHistoryRepository_CreateHistoryEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateHistoryEntry'
type TaskHistoryRepository_CreateHistoryEntry_Call struct {
	*mock.Call
}

// CreateHistoryEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - entry *model.TaskHistory
func (_e *TaskHistoryRepository_Expecter) CreateHistoryEntry(ctx interface{}, tx interface{}, entry interface{}) *TaskHistoryRepository_CreateHistoryEntry_Call {
	return &TaskHistoryRepository_CreateHistoryEntry_Call{Call: _e.mock.On("CreateHistoryEntry", ctx, tx, entry)}
}

func (_c *TaskHistoryRepository_CreateHistoryEntry_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, entry *model.TaskHistory)) *TaskHistoryRepository_CreateHistoryEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(*model.TaskHistory))
	})
	return _c
}

func (_c *TaskHistoryRepository_CreateHistoryEntry_Call) Return(_a0 error) *TaskHistoryRepository_CreateHistoryEntry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TaskHistoryRepository_CreateHistoryEntry_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, *model.TaskHistory) error) *TaskHistoryRepository_CreateHistoryEntry_Call {
	_c.Call.Return(run)
	return _c
}

// ListHistoryByTaskID provides a mock function with given fields: ctx, tx, taskID
func (_m *TaskHistoryRepository) ListHistoryByTaskID(ctx context.Context, tx *sqlx.Tx, taskID uuid.UUID) ([]*model.TaskHistory, error) {
	ret := _m.Called(ctx, tx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for ListHistoryByTaskID")
	}

	var r0 []*model.TaskHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID) ([]*model.TaskHistory, error)); ok {
		return rf(ctx, tx, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID) []*model.TaskHistory); ok {
		r0 = rf(ctx, tx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.TaskHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskHistoryRepository_ListHistoryByTaskID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListHistoryByTaskID'
type TaskHistoryRepository_ListHistoryByTaskID_Call struct {
	*mock.Call
}

// ListHistoryByTaskID is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - taskID uuid.UUID
func (_e *TaskHistoryRepository_Expecter) ListHistoryByTaskID(ctx interface{}, tx interface{}, taskID interface{}) *TaskHistoryRepository_ListHistoryByTaskID_Call {
	return &TaskHistoryRepository_ListHistoryByTaskID_Call{Call: _e.mock.On("ListHistoryByTaskID", ctx, tx, taskID)}
}

func (_c *TaskHistoryRepository_ListHistoryByTaskID_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, taskID uuid.UUID)) *TaskHistoryRepository_ListHistoryByTaskID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TaskHistoryRepository_ListHistoryByTaskID_Call) Return(_a0 []*model.TaskHistory, _a1 error) *TaskHistoryRepository_ListHistoryByTaskID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskHistoryRepository_ListHistoryByTaskID_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID) ([]*model.TaskHistory, error)) *TaskHistoryRepository_ListHistoryByTaskID_Call {
	_c.Call.Return(run)
	return _c
}

// NewTaskHistoryRepository creates a new instance of TaskHistoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskHistoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskHistoryRepository {
	mock := &TaskHistoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
