// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/identity/user/model"
	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"
)

// UserReaderRepository is an autogenerated mock type for the UserReaderRepository type
type UserReaderRepository struct {
	mock.Mock
}

type UserReaderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserReaderRepository) EXPECT() *UserReaderRepository_Expecter {
	return &UserReaderRepository_Expecter{mock: &_m.Mock}
}

// GetByEmail provides a mock function with given fields: ctx, tx, email
func (_m *UserReaderRepository) GetByEmail(ctx context.Context, tx *sqlx.Tx, email string) (*model.User, error) {
	ret := _m.Called(ctx, tx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, string) (*model.User, error)); ok {
		return rf(ctx, tx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, string) *model.User); ok {
		r0 = rf(ctx, tx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, string) error); ok {
		r1 = rf(ctx, tx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserReaderRepository_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type UserReaderRepository_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - email string
func (_e *UserReaderRepository_Expecter) GetByEmail(ctx interface{}, tx interface{}, email interface{}) *UserReaderRepository_GetByEmail_Call {
	return &UserReaderRepository_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, tx, email)}
}

func (_c *UserReaderRepository_GetByEmail_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, email string)) *UserReaderRepository_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(string))
	})
	return _c
}

func (_c *UserReaderRepository_GetByEmail_Call) Return(_a0 *model.User, _a1 error) *UserReaderRepository_GetByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserReaderRepository_GetByEmail_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, string) (*model.User, error)) *UserReaderRepository_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, tx, id
func (_m *UserReaderRepository) GetByID(ctx context.Context, tx *sqlx.Tx, id string) (*model.User, error) {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, string) (*model.User, error)); ok {
		return rf(ctx, tx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, string) *model.User); ok {
		r0 = rf(ctx, tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, string) error); ok {
		r1 = rf(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserReaderRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type UserReaderRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - id string
func (_e *UserReaderRepository_Expecter) GetByID(ctx interface{}, tx interface{}, id interface{}) *UserReaderRepository_GetByID_Call {
	return &UserReaderRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, tx, id)}
}

func (_c *UserReaderRepository_GetByID_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, id string)) *UserReaderRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(string))
	})
	return _c
}

func (_c *UserReaderRepository_GetByID_Call) Return(_a0 *model.User, _a1 error) *UserReaderRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserReaderRepository_GetByID_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, string) (*model.User, error)) *UserReaderRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserReaderRepository creates a new instance of UserReaderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserReaderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserReaderRepository {
	mock := &UserReaderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
