// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/identity/user/model"
	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"
)

// UserWriterRepository is an autogenerated mock type for the UserWriterRepository type
type UserWriterRepository struct {
	mock.Mock
}

type UserWriterRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserWriterRepository) EXPECT() *UserWriterRepository_Expecter {
	return &UserWriterRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, tx, input, passwordHash
func (_m *UserWriterRepository) Create(ctx context.Context, tx *sqlx.Tx, input *model.UserInput, passwordHash string) (*model.User, error) {
	ret := _m.Called(ctx, tx, input, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *model.UserInput, string) (*model.User, error)); ok {
		return rf(ctx, tx, input, passwordHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *model.UserInput, string) *model.User); ok {
		r0 = rf(ctx, tx, input, passwordHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, *model.UserInput, string) error); ok {
		r1 = rf(ctx, tx, input, passwordHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserWriterRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserWriterRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - input *model.UserInput
//   - passwordHash string
func (_e *UserWriterRepository_Expecter) Create(ctx interface{}, tx interface{}, input interface{}, passwordHash interface{}) *UserWriterRepository_Create_Call {
	return &UserWriterRepository_Create_Call{Call: _e.mock.On("Create", ctx, tx, input, passwordHash)}
}

func (_c *UserWriterRepository_Create_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, input *model.UserInput, passwordHash string)) *UserWriterRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(*model.UserInput), args[3].(string))
	})
	return _c
}

func (_c *UserWriterRepository_Create_Call) Return(_a0 *model.User, _a1 error) *UserWriterRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserWriterRepository_Create_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, *model.UserInput, string) (*model.User, error)) *UserWriterRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, tx, id
func (_m *UserWriterRepository) Delete(ctx context.Context, tx *sqlx.Tx, id string) error {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, string) error); ok {
		r0 = rf(ctx, tx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserWriterRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type UserWriterRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - id string
func (_e *UserWriterRepository_Expecter) Delete(ctx interface{}, tx interface{}, id interface{}) *UserWriterRepository_Delete_Call {
	return &UserWriterRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, tx, id)}
}

func (_c *UserWriterRepository_Delete_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, id string)) *UserWriterRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(string))
	})
	return _c
}

func (_c *UserWriterRepository_Delete_Call) Return(_a0 error) *UserWriterRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserWriterRepository_Delete_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, string) error) *UserWriterRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, tx, id, input
func (_m *UserWriterRepository) Update(ctx context.Context, tx *sqlx.Tx, id string, input *model.UserInput) (*model.User, error) {
	ret := _m.Called(ctx, tx, id, input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, string, *model.UserInput) (*model.User, error)); ok {
		return rf(ctx, tx, id, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, string, *model.UserInput) *model.User); ok {
		r0 = rf(ctx, tx, id, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, string, *model.UserInput) error); ok {
		r1 = rf(ctx, tx, id, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserWriterRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type UserWriterRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - id string
//   - input *model.UserInput
func (_e *UserWriterRepository_Expecter) Update(ctx interface{}, tx interface{}, id interface{}, input interface{}) *UserWriterRepository_Update_Call {
	return &UserWriterRepository_Update_Call{Call: _e.mock.On("Update", ctx, tx, id, input)}
}

func (_c *UserWriterRepository_Update_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, id string, input *model.UserInput)) *UserWriterRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(string), args[3].(*model.UserInput))
	})
	return _c
}

func (_c *UserWriterRepository_Update_Call) Return(_a0 *model.User, _a1 error) *UserWriterRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserWriterRepository_Update_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, string, *model.UserInput) (*model.User, error)) *UserWriterRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePasswordHash provides a mock function with given fields: ctx, tx, id, passwordHash
func (_m *UserWriterRepository) UpdatePasswordHash(ctx context.Context, tx *sqlx.Tx, id string, passwordHash string) error {
	ret := _m.Called(ctx, tx, id, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePasswordHash")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, string, string) error); ok {
		r0 = rf(ctx, tx, id, passwordHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserWriterRepository_UpdatePasswordHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePasswordHash'
type UserWriterRepository_UpdatePasswordHash_Call struct {
	*mock.Call
}

// UpdatePasswordHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - id string
//   - passwordHash string
func (_e *UserWriterRepository_Expecter) UpdatePasswordHash(ctx interface{}, tx interface{}, id interface{}, passwordHash interface{}) *UserWriterRepository_UpdatePasswordHash_Call {
	return &UserWriterRepository_UpdatePasswordHash_Call{Call: _e.mock.On("UpdatePasswordHash", ctx, tx, id, passwordHash)}
}

func (_c *UserWriterRepository_UpdatePasswordHash_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, id string, passwordHash string)) *UserWriterRepository_UpdatePasswordHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *UserWriterRepository_UpdatePasswordHash_Call) Return(_a0 error) *UserWriterRepository_UpdatePasswordHash_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserWriterRepository_UpdatePasswordHash_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, string, string) error) *UserWriterRepository_UpdatePasswordHash_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserWriterRepository creates a new instance of UserWriterRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserWriterRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserWriterRepository {
	mock := &UserWriterRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
