// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/workspace/team/model"
	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"

	uuid "github.com/google/uuid"
)

// MemberWriterRepository is an autogenerated mock type for the MemberWriterRepository type
type MemberWriterRepository struct {
	mock.Mock
}

type MemberWriterRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MemberWriterRepository) EXPECT() *MemberWriterRepository_Expecter {
	return &MemberWriterRepository_Expecter{mock: &_m.Mock}
}

// AddMember provides a mock function with given fields: ctx, tx, teamID, userID, role
func (_m *MemberWriterRepository) AddMember(ctx context.Context, tx *sqlx.Tx, teamID uuid.UUID, userID uuid.UUID, role string) (model.TeamMember, error) {
	ret := _m.Called(ctx, tx, teamID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 model.TeamMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID, string) (model.TeamMember, error)); ok {
		return rf(ctx, tx, teamID, userID, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID, string) model.TeamMember); ok {
		r0 = rf(ctx, tx, teamID, userID, role)
	} else {
		r0 = ret.Get(0).(model.TeamMember)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = rf(ctx, tx, teamID, userID, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MemberWriterRepository_AddMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMember'
type MemberWriterRepository_AddMember_Call struct {
	*mock.Call
}

// AddMember is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - teamID uuid.UUID
//   - userID uuid.UUID
//   - role string
func (_e *MemberWriterRepository_Expecter) AddMember(ctx interface{}, tx interface{}, teamID interface{}, userID interface{}, role interface{}) *MemberWriterRepository_AddMember_Call {
	return &MemberWriterRepository_AddMember_Call{Call: _e.mock.On("AddMember", ctx, tx, teamID, userID, role)}
}

func (_c *MemberWriterRepository_AddMember_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, teamID uuid.UUID, userID uuid.UUID, role string)) *MemberWriterRepository_AddMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID), args[3].(uuid.UUID), args[4].(string))
	})
	return _c
}

func (_c *MemberWriterRepository_AddMember_Call) Return(_a0 model.TeamMember, _a1 error) *MemberWriterRepository_AddMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MemberWriterRepository_AddMember_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID, string) (model.TeamMember, error)) *MemberWriterRepository_AddMember_Call {
	_c.Call.Return(run)
	return _c
}

// NewMemberWriterRepository creates a new instance of MemberWriterRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMemberWriterRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MemberWriterRepository {
	mock := &MemberWriterRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
