// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/workspace/team/model"
	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"

	uuid "github.com/google/uuid"
)

// MemberReaderRepository is an autogenerated mock type for the MemberReaderRepository type
type MemberReaderRepository struct {
	mock.Mock
}

type MemberReaderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MemberReaderRepository) EXPECT() *MemberReaderRepository_Expecter {
	return &MemberReaderRepository_Expecter{mock: &_m.Mock}
}

// GetByTeamID provides a mock function with given fields: ctx, tx, teamID
func (_m *MemberReaderRepository) GetByTeamID(ctx context.Context, tx *sqlx.Tx, teamID uuid.UUID) ([]*model.TeamMember, error) {
	ret := _m.Called(ctx, tx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetByTeamID")
	}

	var r0 []*model.TeamMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID) ([]*model.TeamMember, error)); ok {
		return rf(ctx, tx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID) []*model.TeamMember); ok {
		r0 = rf(ctx, tx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.TeamMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MemberReaderRepository_GetByTeamID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTeamID'
type MemberReaderRepository_GetByTeamID_Call struct {
	*mock.Call
}

// GetByTeamID is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - teamID uuid.UUID
func (_e *MemberReaderRepository_Expecter) GetByTeamID(ctx interface{}, tx interface{}, teamID interface{}) *MemberReaderRepository_GetByTeamID_Call {
	return &MemberReaderRepository_GetByTeamID_Call{Call: _e.mock.On("GetByTeamID", ctx, tx, teamID)}
}

func (_c *MemberReaderRepository_GetByTeamID_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, teamID uuid.UUID)) *MemberReaderRepository_GetByTeamID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MemberReaderRepository_GetByTeamID_Call) Return(_a0 []*model.TeamMember, _a1 error) *MemberReaderRepository_GetByTeamID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MemberReaderRepository_GetByTeamID_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID) ([]*model.TeamMember, error)) *MemberReaderRepository_GetByTeamID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMember provides a mock function with given fields: ctx, tx, teamID, userID
func (_m *MemberReaderRepository) GetMember(ctx context.Context, tx *sqlx.Tx, teamID uuid.UUID, userID uuid.UUID) (*model.TeamMember, error) {
	ret := _m.Called(ctx, tx, teamID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMember")
	}

	var r0 *model.TeamMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID) (*model.TeamMember, error)); ok {
		return rf(ctx, tx, teamID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID) *model.TeamMember); ok {
		r0 = rf(ctx, tx, teamID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TeamMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, teamID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MemberReaderRepository_GetMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMember'
type MemberReaderRepository_GetMember_Call struct {
	*mock.Call
}

// GetMember is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - teamID uuid.UUID
//   - userID uuid.UUID
func (_e *MemberReaderRepository_Expecter) GetMember(ctx interface{}, tx interface{}, teamID interface{}, userID interface{}) *MemberReaderRepository_GetMember_Call {
	return &MemberReaderRepository_GetMember_Call{Call: _e.mock.On("GetMember", ctx, tx, teamID, userID)}
}

func (_c *MemberReaderRepository_GetMember_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, teamID uuid.UUID, userID uuid.UUID)) *MemberReaderRepository_GetMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MemberReaderRepository_GetMember_Call) Return(_a0 *model.TeamMember, _a1 error) *MemberReaderRepository_GetMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MemberReaderRepository_GetMember_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID) (*model.TeamMember, error)) *MemberReaderRepository_GetMember_Call {
	_c.Call.Return(run)
	return _c
}

// NewMemberReaderRepository creates a new instance of MemberReaderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMemberReaderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MemberReaderRepository {
	mock := &MemberReaderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
