// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/workspace/team/model"
	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"

	uuid "github.com/google/uuid"
)

// MemberRepository is an autogenerated mock type for the MemberRepository type
type MemberRepository struct {
	mock.Mock
}

type MemberRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MemberRepository) EXPECT() *MemberRepository_Expecter {
	return &MemberRepository_Expecter{mock: &_m.Mock}
}

// AddMember provides a mock function with given fields: ctx, tx, teamID, userID, role
func (_m *MemberRepository) AddMember(ctx context.Context, tx *sqlx.Tx, teamID uuid.UUID, userID uuid.UUID, role string) (model.TeamMember, error) {
	ret := _m.Called(ctx, tx, teamID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 model.TeamMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID, string) (model.TeamMember, error)); ok {
		return rf(ctx, tx, teamID, userID, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID, string) model.TeamMember); ok {
		r0 = rf(ctx, tx, teamID, userID, role)
	} else {
		r0 = ret.Get(0).(model.TeamMember)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = rf(ctx, tx, teamID, userID, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MemberRepository_AddMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMember'
type MemberRepository_AddMember_Call struct {
	*mock.Call
}

// AddMember is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - teamID uuid.UUID
//   - userID uuid.UUID
//   - role string
func (_e *MemberRepository_Expecter) AddMember(ctx interface{}, tx interface{}, teamID interface{}, userID interface{}, role interface{}) *MemberRepository_AddMember_Call {
	return &MemberRepository_AddMember_Call{Call: _e.mock.On("AddMember", ctx, tx, teamID, userID, role)}
}

func (_c *MemberRepository_AddMember_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, teamID uuid.UUID, userID uuid.UUID, role string)) *MemberRepository_AddMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID), args[3].(uuid.UUID), args[4].(string))
	})
	return _c
}

func (_c *MemberRepository_AddMember_Call) Return(_a0 model.TeamMember, _a1 error) *MemberRepository_AddMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MemberRepository_AddMember_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID, string) (model.TeamMember, error)) *MemberRepository_AddMember_Call {
	_c.Call.Return(run)
	return _c
}

// GetMember provides a mock function with given fields: ctx, tx, teamID, userID
func (_m *MemberRepository) GetMember(ctx context.Context, tx *sqlx.Tx, teamID uuid.UUID, userID uuid.UUID) (model.TeamMember, error) {
	ret := _m.Called(ctx, tx, teamID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMember")
	}

	var r0 model.TeamMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID) (model.TeamMember, error)); ok {
		return rf(ctx, tx, teamID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID) model.TeamMember); ok {
		r0 = rf(ctx, tx, teamID, userID)
	} else {
		r0 = ret.Get(0).(model.TeamMember)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, teamID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MemberRepository_GetMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMember'
type MemberRepository_GetMember_Call struct {
	*mock.Call
}

// GetMember is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - teamID uuid.UUID
//   - userID uuid.UUID
func (_e *MemberRepository_Expecter) GetMember(ctx interface{}, tx interface{}, teamID interface{}, userID interface{}) *MemberRepository_GetMember_Call {
	return &MemberRepository_GetMember_Call{Call: _e.mock.On("GetMember", ctx, tx, teamID, userID)}
}

func (_c *MemberRepository_GetMember_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, teamID uuid.UUID, userID uuid.UUID)) *MemberRepository_GetMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MemberRepository_GetMember_Call) Return(_a0 model.TeamMember, _a1 error) *MemberRepository_GetMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MemberRepository_GetMember_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID) (model.TeamMember, error)) *MemberRepository_GetMember_Call {
	_c.Call.Return(run)
	return _c
}

// GetMembersByTeamID provides a mock function with given fields: ctx, tx, teamID
func (_m *MemberRepository) GetMembersByTeamID(ctx context.Context, tx *sqlx.Tx, teamID uuid.UUID) ([]model.TeamMember, error) {
	ret := _m.Called(ctx, tx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetMembersByTeamID")
	}

	var r0 []model.TeamMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID) ([]model.TeamMember, error)); ok {
		return rf(ctx, tx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID) []model.TeamMember); ok {
		r0 = rf(ctx, tx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.TeamMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MemberRepository_GetMembersByTeamID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMembersByTeamID'
type MemberRepository_GetMembersByTeamID_Call struct {
	*mock.Call
}

// GetMembersByTeamID is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - teamID uuid.UUID
func (_e *MemberRepository_Expecter) GetMembersByTeamID(ctx interface{}, tx interface{}, teamID interface{}) *MemberRepository_GetMembersByTeamID_Call {
	return &MemberRepository_GetMembersByTeamID_Call{Call: _e.mock.On("GetMembersByTeamID", ctx, tx, teamID)}
}

func (_c *MemberRepository_GetMembersByTeamID_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, teamID uuid.UUID)) *MemberRepository_GetMembersByTeamID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MemberRepository_GetMembersByTeamID_Call) Return(_a0 []model.TeamMember, _a1 error) *MemberRepository_GetMembersByTeamID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MemberRepository_GetMembersByTeamID_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID) ([]model.TeamMember, error)) *MemberRepository_GetMembersByTeamID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMemberRepository creates a new instance of MemberRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMemberRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MemberRepository {
	mock := &MemberRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
