// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model2 "github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/workspace/team/model"
	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"

	uuid "github.com/google/uuid"
)

// TeamRepository is an autogenerated mock type for the TeamRepository type
type TeamRepository struct {
	mock.Mock
}

type TeamRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TeamRepository) EXPECT() *TeamRepository_Expecter {
	return &TeamRepository_Expecter{mock: &_m.Mock}
}

// AddMember provides a mock function with given fields: ctx, tx, teamID, userID, role
func (_m *TeamRepository) AddMember(ctx context.Context, tx *sqlx.Tx, teamID uuid.UUID, userID uuid.UUID, role string) (*model2.TeamMember, error) {
	ret := _m.Called(ctx, tx, teamID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 *model2.TeamMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID, string) (*model2.TeamMember, error)); ok {
		return rf(ctx, tx, teamID, userID, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID, string) *model2.TeamMember); ok {
		r0 = rf(ctx, tx, teamID, userID, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model2.TeamMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = rf(ctx, tx, teamID, userID, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamRepository_AddMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMember'
type TeamRepository_AddMember_Call struct {
	*mock.Call
}

// AddMember is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - teamID uuid.UUID
//   - userID uuid.UUID
//   - role string
func (_e *TeamRepository_Expecter) AddMember(ctx interface{}, tx interface{}, teamID interface{}, userID interface{}, role interface{}) *TeamRepository_AddMember_Call {
	return &TeamRepository_AddMember_Call{Call: _e.mock.On("AddMember", ctx, tx, teamID, userID, role)}
}

func (_c *TeamRepository_AddMember_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, teamID uuid.UUID, userID uuid.UUID, role string)) *TeamRepository_AddMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID), args[3].(uuid.UUID), args[4].(string))
	})
	return _c
}

func (_c *TeamRepository_AddMember_Call) Return(_a0 *model2.TeamMember, _a1 error) *TeamRepository_AddMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamRepository_AddMember_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID, string) (*model2.TeamMember, error)) *TeamRepository_AddMember_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, tx, input, ownerUserID
func (_m *TeamRepository) Create(ctx context.Context, tx *sqlx.Tx, input *model2.TeamInput, ownerUserID uuid.UUID) (*model2.Team, error) {
	ret := _m.Called(ctx, tx, input, ownerUserID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model2.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *model2.TeamInput, uuid.UUID) (*model2.Team, error)); ok {
		return rf(ctx, tx, input, ownerUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *model2.TeamInput, uuid.UUID) *model2.Team); ok {
		r0 = rf(ctx, tx, input, ownerUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model2.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, *model2.TeamInput, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, input, ownerUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TeamRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - input *model.TeamInput
//   - ownerUserID uuid.UUID
func (_e *TeamRepository_Expecter) Create(ctx interface{}, tx interface{}, input interface{}, ownerUserID interface{}) *TeamRepository_Create_Call {
	return &TeamRepository_Create_Call{Call: _e.mock.On("Create", ctx, tx, input, ownerUserID)}
}

func (_c *TeamRepository_Create_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, input *model2.TeamInput, ownerUserID uuid.UUID)) *TeamRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(*model2.TeamInput), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *TeamRepository_Create_Call) Return(_a0 *model2.Team, _a1 error) *TeamRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamRepository_Create_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, *model2.TeamInput, uuid.UUID) (*model2.Team, error)) *TeamRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInvitation provides a mock function with given fields: ctx, tx, inv
func (_m *TeamRepository) CreateInvitation(ctx context.Context, tx *sqlx.Tx, inv *model2.TeamInvitation) error {
	ret := _m.Called(ctx, tx, inv)

	if len(ret) == 0 {
		panic("no return value specified for CreateInvitation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *model2.TeamInvitation) error); ok {
		r0 = rf(ctx, tx, inv)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TeamRepository_CreateInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInvitation'
type TeamRepository_CreateInvitation_Call struct {
	*mock.Call
}

// CreateInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - inv *model.TeamInvitation
func (_e *TeamRepository_Expecter) CreateInvitation(ctx interface{}, tx interface{}, inv interface{}) *TeamRepository_CreateInvitation_Call {
	return &TeamRepository_CreateInvitation_Call{Call: _e.mock.On("CreateInvitation", ctx, tx, inv)}
}

func (_c *TeamRepository_CreateInvitation_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, inv *model2.TeamInvitation)) *TeamRepository_CreateInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(*model2.TeamInvitation))
	})
	return _c
}

func (_c *TeamRepository_CreateInvitation_Call) Return(_a0 error) *TeamRepository_CreateInvitation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeamRepository_CreateInvitation_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, *model2.TeamInvitation) error) *TeamRepository_CreateInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, tx, teamID
func (_m *TeamRepository) GetByID(ctx context.Context, tx *sqlx.Tx, teamID uuid.UUID) (*model2.Team, error) {
	ret := _m.Called(ctx, tx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model2.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID) (*model2.Team, error)); ok {
		return rf(ctx, tx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID) *model2.Team); ok {
		r0 = rf(ctx, tx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model2.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type TeamRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - teamID uuid.UUID
func (_e *TeamRepository_Expecter) GetByID(ctx interface{}, tx interface{}, teamID interface{}) *TeamRepository_GetByID_Call {
	return &TeamRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, tx, teamID)}
}

func (_c *TeamRepository_GetByID_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, teamID uuid.UUID)) *TeamRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TeamRepository_GetByID_Call) Return(_a0 *model2.Team, _a1 error) *TeamRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamRepository_GetByID_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID) (*model2.Team, error)) *TeamRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMember provides a mock function with given fields: ctx, tx, teamID, userID
func (_m *TeamRepository) GetMember(ctx context.Context, tx *sqlx.Tx, teamID uuid.UUID, userID uuid.UUID) (*model2.TeamMember, error) {
	ret := _m.Called(ctx, tx, teamID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMember")
	}

	var r0 *model2.TeamMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID) (*model2.TeamMember, error)); ok {
		return rf(ctx, tx, teamID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID) *model2.TeamMember); ok {
		r0 = rf(ctx, tx, teamID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model2.TeamMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, teamID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamRepository_GetMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMember'
type TeamRepository_GetMember_Call struct {
	*mock.Call
}

// GetMember is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - teamID uuid.UUID
//   - userID uuid.UUID
func (_e *TeamRepository_Expecter) GetMember(ctx interface{}, tx interface{}, teamID interface{}, userID interface{}) *TeamRepository_GetMember_Call {
	return &TeamRepository_GetMember_Call{Call: _e.mock.On("GetMember", ctx, tx, teamID, userID)}
}

func (_c *TeamRepository_GetMember_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, teamID uuid.UUID, userID uuid.UUID)) *TeamRepository_GetMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *TeamRepository_GetMember_Call) Return(_a0 *model2.TeamMember, _a1 error) *TeamRepository_GetMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamRepository_GetMember_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID) (*model2.TeamMember, error)) *TeamRepository_GetMember_Call {
	_c.Call.Return(run)
	return _c
}

// GetMembersByTeamID provides a mock function with given fields: ctx, tx, teamID
func (_m *TeamRepository) GetMembersByTeamID(ctx context.Context, tx *sqlx.Tx, teamID uuid.UUID) ([]*model2.TeamMember, error) {
	ret := _m.Called(ctx, tx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetMembersByTeamID")
	}

	var r0 []*model2.TeamMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID) ([]*model2.TeamMember, error)); ok {
		return rf(ctx, tx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID) []*model2.TeamMember); ok {
		r0 = rf(ctx, tx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model2.TeamMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamRepository_GetMembersByTeamID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMembersByTeamID'
type TeamRepository_GetMembersByTeamID_Call struct {
	*mock.Call
}

// GetMembersByTeamID is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - teamID uuid.UUID
func (_e *TeamRepository_Expecter) GetMembersByTeamID(ctx interface{}, tx interface{}, teamID interface{}) *TeamRepository_GetMembersByTeamID_Call {
	return &TeamRepository_GetMembersByTeamID_Call{Call: _e.mock.On("GetMembersByTeamID", ctx, tx, teamID)}
}

func (_c *TeamRepository_GetMembersByTeamID_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, teamID uuid.UUID)) *TeamRepository_GetMembersByTeamID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TeamRepository_GetMembersByTeamID_Call) Return(_a0 []*model2.TeamMember, _a1 error) *TeamRepository_GetMembersByTeamID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamRepository_GetMembersByTeamID_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID) ([]*model2.TeamMember, error)) *TeamRepository_GetMembersByTeamID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingInvitationByTeamAndEmail provides a mock function with given fields: ctx, tx, teamID, email
func (_m *TeamRepository) GetPendingInvitationByTeamAndEmail(ctx context.Context, tx *sqlx.Tx, teamID uuid.UUID, email string) (*model2.TeamInvitation, error) {
	ret := _m.Called(ctx, tx, teamID, email)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingInvitationByTeamAndEmail")
	}

	var r0 *model2.TeamInvitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, string) (*model2.TeamInvitation, error)); ok {
		return rf(ctx, tx, teamID, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, string) *model2.TeamInvitation); ok {
		r0 = rf(ctx, tx, teamID, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model2.TeamInvitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, uuid.UUID, string) error); ok {
		r1 = rf(ctx, tx, teamID, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamRepository_GetPendingInvitationByTeamAndEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingInvitationByTeamAndEmail'
type TeamRepository_GetPendingInvitationByTeamAndEmail_Call struct {
	*mock.Call
}

// GetPendingInvitationByTeamAndEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - teamID uuid.UUID
//   - email string
func (_e *TeamRepository_Expecter) GetPendingInvitationByTeamAndEmail(ctx interface{}, tx interface{}, teamID interface{}, email interface{}) *TeamRepository_GetPendingInvitationByTeamAndEmail_Call {
	return &TeamRepository_GetPendingInvitationByTeamAndEmail_Call{Call: _e.mock.On("GetPendingInvitationByTeamAndEmail", ctx, tx, teamID, email)}
}

func (_c *TeamRepository_GetPendingInvitationByTeamAndEmail_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, teamID uuid.UUID, email string)) *TeamRepository_GetPendingInvitationByTeamAndEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *TeamRepository_GetPendingInvitationByTeamAndEmail_Call) Return(_a0 *model2.TeamInvitation, _a1 error) *TeamRepository_GetPendingInvitationByTeamAndEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamRepository_GetPendingInvitationByTeamAndEmail_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID, string) (*model2.TeamInvitation, error)) *TeamRepository_GetPendingInvitationByTeamAndEmail_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function with given fields: ctx, tx, userID
func (_m *TeamRepository) ListByUserID(ctx context.Context, tx *sqlx.Tx, userID uuid.UUID) ([]*model2.TeamWithRole, error) {
	ret := _m.Called(ctx, tx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []*model2.TeamWithRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID) ([]*model2.TeamWithRole, error)); ok {
		return rf(ctx, tx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID) []*model2.TeamWithRole); ok {
		r0 = rf(ctx, tx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model2.TeamWithRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamRepository_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type TeamRepository_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - userID uuid.UUID
func (_e *TeamRepository_Expecter) ListByUserID(ctx interface{}, tx interface{}, userID interface{}) *TeamRepository_ListByUserID_Call {
	return &TeamRepository_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, tx, userID)}
}

func (_c *TeamRepository_ListByUserID_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, userID uuid.UUID)) *TeamRepository_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TeamRepository_ListByUserID_Call) Return(_a0 []*model2.TeamWithRole, _a1 error) *TeamRepository_ListByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamRepository_ListByUserID_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID) ([]*model2.TeamWithRole, error)) *TeamRepository_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewTeamRepository creates a new instance of TeamRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamRepository {
	mock := &TeamRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
