// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/workspace/team/model"
	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"

	uuid "github.com/google/uuid"
)

// InvitationRepository is an autogenerated mock type for the InvitationRepository type
type InvitationRepository struct {
	mock.Mock
}

type InvitationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *InvitationRepository) EXPECT() *InvitationRepository_Expecter {
	return &InvitationRepository_Expecter{mock: &_m.Mock}
}

// CreateInvitation provides a mock function with given fields: ctx, tx, inv
func (_m *InvitationRepository) CreateInvitation(ctx context.Context, tx *sqlx.Tx, inv model.TeamInvitation) error {
	ret := _m.Called(ctx, tx, inv)

	if len(ret) == 0 {
		panic("no return value specified for CreateInvitation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, model.TeamInvitation) error); ok {
		r0 = rf(ctx, tx, inv)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InvitationRepository_CreateInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInvitation'
type InvitationRepository_CreateInvitation_Call struct {
	*mock.Call
}

// CreateInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - inv model.TeamInvitation
func (_e *InvitationRepository_Expecter) CreateInvitation(ctx interface{}, tx interface{}, inv interface{}) *InvitationRepository_CreateInvitation_Call {
	return &InvitationRepository_CreateInvitation_Call{Call: _e.mock.On("CreateInvitation", ctx, tx, inv)}
}

func (_c *InvitationRepository_CreateInvitation_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, inv model.TeamInvitation)) *InvitationRepository_CreateInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(model.TeamInvitation))
	})
	return _c
}

func (_c *InvitationRepository_CreateInvitation_Call) Return(_a0 error) *InvitationRepository_CreateInvitation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InvitationRepository_CreateInvitation_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, model.TeamInvitation) error) *InvitationRepository_CreateInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingInvitationByTeamAndEmail provides a mock function with given fields: ctx, tx, teamID, email
func (_m *InvitationRepository) GetPendingInvitationByTeamAndEmail(ctx context.Context, tx *sqlx.Tx, teamID uuid.UUID, email string) (model.TeamInvitation, error) {
	ret := _m.Called(ctx, tx, teamID, email)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingInvitationByTeamAndEmail")
	}

	var r0 model.TeamInvitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, string) (model.TeamInvitation, error)); ok {
		return rf(ctx, tx, teamID, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, string) model.TeamInvitation); ok {
		r0 = rf(ctx, tx, teamID, email)
	} else {
		r0 = ret.Get(0).(model.TeamInvitation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, uuid.UUID, string) error); ok {
		r1 = rf(ctx, tx, teamID, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InvitationRepository_GetPendingInvitationByTeamAndEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingInvitationByTeamAndEmail'
type InvitationRepository_GetPendingInvitationByTeamAndEmail_Call struct {
	*mock.Call
}

// GetPendingInvitationByTeamAndEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - teamID uuid.UUID
//   - email string
func (_e *InvitationRepository_Expecter) GetPendingInvitationByTeamAndEmail(ctx interface{}, tx interface{}, teamID interface{}, email interface{}) *InvitationRepository_GetPendingInvitationByTeamAndEmail_Call {
	return &InvitationRepository_GetPendingInvitationByTeamAndEmail_Call{Call: _e.mock.On("GetPendingInvitationByTeamAndEmail", ctx, tx, teamID, email)}
}

func (_c *InvitationRepository_GetPendingInvitationByTeamAndEmail_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, teamID uuid.UUID, email string)) *InvitationRepository_GetPendingInvitationByTeamAndEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *InvitationRepository_GetPendingInvitationByTeamAndEmail_Call) Return(_a0 model.TeamInvitation, _a1 error) *InvitationRepository_GetPendingInvitationByTeamAndEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InvitationRepository_GetPendingInvitationByTeamAndEmail_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID, string) (model.TeamInvitation, error)) *InvitationRepository_GetPendingInvitationByTeamAndEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewInvitationRepository creates a new instance of InvitationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInvitationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InvitationRepository {
	mock := &InvitationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
