// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/workspace/team/model"
	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"

	uuid "github.com/google/uuid"
)

// TeamAdapter is an autogenerated mock type for the TeamAdapter type
type TeamAdapter struct {
	mock.Mock
}

type TeamAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *TeamAdapter) EXPECT() *TeamAdapter_Expecter {
	return &TeamAdapter_Expecter{mock: &_m.Mock}
}

// AddMember provides a mock function with given fields: ctx, tx, teamID, userID, role
func (_m *TeamAdapter) AddMember(ctx context.Context, tx *sqlx.Tx, teamID uuid.UUID, userID uuid.UUID, role string) (*model.TeamMember, error) {
	ret := _m.Called(ctx, tx, teamID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 *model.TeamMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID, string) (*model.TeamMember, error)); ok {
		return rf(ctx, tx, teamID, userID, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID, string) *model.TeamMember); ok {
		r0 = rf(ctx, tx, teamID, userID, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TeamMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = rf(ctx, tx, teamID, userID, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamAdapter_AddMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMember'
type TeamAdapter_AddMember_Call struct {
	*mock.Call
}

// AddMember is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - teamID uuid.UUID
//   - userID uuid.UUID
//   - role string
func (_e *TeamAdapter_Expecter) AddMember(ctx interface{}, tx interface{}, teamID interface{}, userID interface{}, role interface{}) *TeamAdapter_AddMember_Call {
	return &TeamAdapter_AddMember_Call{Call: _e.mock.On("AddMember", ctx, tx, teamID, userID, role)}
}

func (_c *TeamAdapter_AddMember_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, teamID uuid.UUID, userID uuid.UUID, role string)) *TeamAdapter_AddMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID), args[3].(uuid.UUID), args[4].(string))
	})
	return _c
}

func (_c *TeamAdapter_AddMember_Call) Return(_a0 *model.TeamMember, _a1 error) *TeamAdapter_AddMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamAdapter_AddMember_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID, string) (*model.TeamMember, error)) *TeamAdapter_AddMember_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, tx, input, ownerUserID
func (_m *TeamAdapter) Create(ctx context.Context, tx *sqlx.Tx, input *model.TeamInput, ownerUserID uuid.UUID) (*model.Team, error) {
	ret := _m.Called(ctx, tx, input, ownerUserID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *model.TeamInput, uuid.UUID) (*model.Team, error)); ok {
		return rf(ctx, tx, input, ownerUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *model.TeamInput, uuid.UUID) *model.Team); ok {
		r0 = rf(ctx, tx, input, ownerUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, *model.TeamInput, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, input, ownerUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamAdapter_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TeamAdapter_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - input *model.TeamInput
//   - ownerUserID uuid.UUID
func (_e *TeamAdapter_Expecter) Create(ctx interface{}, tx interface{}, input interface{}, ownerUserID interface{}) *TeamAdapter_Create_Call {
	return &TeamAdapter_Create_Call{Call: _e.mock.On("Create", ctx, tx, input, ownerUserID)}
}

func (_c *TeamAdapter_Create_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, input *model.TeamInput, ownerUserID uuid.UUID)) *TeamAdapter_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(*model.TeamInput), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *TeamAdapter_Create_Call) Return(_a0 *model.Team, _a1 error) *TeamAdapter_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamAdapter_Create_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, *model.TeamInput, uuid.UUID) (*model.Team, error)) *TeamAdapter_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInvitation provides a mock function with given fields: ctx, tx, inv
func (_m *TeamAdapter) CreateInvitation(ctx context.Context, tx *sqlx.Tx, inv *model.TeamInvitation) error {
	ret := _m.Called(ctx, tx, inv)

	if len(ret) == 0 {
		panic("no return value specified for CreateInvitation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *model.TeamInvitation) error); ok {
		r0 = rf(ctx, tx, inv)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TeamAdapter_CreateInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInvitation'
type TeamAdapter_CreateInvitation_Call struct {
	*mock.Call
}

// CreateInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - inv *model.TeamInvitation
func (_e *TeamAdapter_Expecter) CreateInvitation(ctx interface{}, tx interface{}, inv interface{}) *TeamAdapter_CreateInvitation_Call {
	return &TeamAdapter_CreateInvitation_Call{Call: _e.mock.On("CreateInvitation", ctx, tx, inv)}
}

func (_c *TeamAdapter_CreateInvitation_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, inv *model.TeamInvitation)) *TeamAdapter_CreateInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(*model.TeamInvitation))
	})
	return _c
}

func (_c *TeamAdapter_CreateInvitation_Call) Return(_a0 error) *TeamAdapter_CreateInvitation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeamAdapter_CreateInvitation_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, *model.TeamInvitation) error) *TeamAdapter_CreateInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, tx, teamID
func (_m *TeamAdapter) GetByID(ctx context.Context, tx *sqlx.Tx, teamID uuid.UUID) (*model.Team, error) {
	ret := _m.Called(ctx, tx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID) (*model.Team, error)); ok {
		return rf(ctx, tx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID) *model.Team); ok {
		r0 = rf(ctx, tx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamAdapter_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type TeamAdapter_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - teamID uuid.UUID
func (_e *TeamAdapter_Expecter) GetByID(ctx interface{}, tx interface{}, teamID interface{}) *TeamAdapter_GetByID_Call {
	return &TeamAdapter_GetByID_Call{Call: _e.mock.On("GetByID", ctx, tx, teamID)}
}

func (_c *TeamAdapter_GetByID_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, teamID uuid.UUID)) *TeamAdapter_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TeamAdapter_GetByID_Call) Return(_a0 *model.Team, _a1 error) *TeamAdapter_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamAdapter_GetByID_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID) (*model.Team, error)) *TeamAdapter_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMember provides a mock function with given fields: ctx, tx, teamID, userID
func (_m *TeamAdapter) GetMember(ctx context.Context, tx *sqlx.Tx, teamID uuid.UUID, userID uuid.UUID) (*model.TeamMember, error) {
	ret := _m.Called(ctx, tx, teamID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMember")
	}

	var r0 *model.TeamMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID) (*model.TeamMember, error)); ok {
		return rf(ctx, tx, teamID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID) *model.TeamMember); ok {
		r0 = rf(ctx, tx, teamID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TeamMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, teamID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamAdapter_GetMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMember'
type TeamAdapter_GetMember_Call struct {
	*mock.Call
}

// GetMember is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - teamID uuid.UUID
//   - userID uuid.UUID
func (_e *TeamAdapter_Expecter) GetMember(ctx interface{}, tx interface{}, teamID interface{}, userID interface{}) *TeamAdapter_GetMember_Call {
	return &TeamAdapter_GetMember_Call{Call: _e.mock.On("GetMember", ctx, tx, teamID, userID)}
}

func (_c *TeamAdapter_GetMember_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, teamID uuid.UUID, userID uuid.UUID)) *TeamAdapter_GetMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *TeamAdapter_GetMember_Call) Return(_a0 *model.TeamMember, _a1 error) *TeamAdapter_GetMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamAdapter_GetMember_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID, uuid.UUID) (*model.TeamMember, error)) *TeamAdapter_GetMember_Call {
	_c.Call.Return(run)
	return _c
}

// GetMembersByTeamID provides a mock function with given fields: ctx, tx, teamID
func (_m *TeamAdapter) GetMembersByTeamID(ctx context.Context, tx *sqlx.Tx, teamID uuid.UUID) ([]*model.TeamMember, error) {
	ret := _m.Called(ctx, tx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetMembersByTeamID")
	}

	var r0 []*model.TeamMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID) ([]*model.TeamMember, error)); ok {
		return rf(ctx, tx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID) []*model.TeamMember); ok {
		r0 = rf(ctx, tx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.TeamMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamAdapter_GetMembersByTeamID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMembersByTeamID'
type TeamAdapter_GetMembersByTeamID_Call struct {
	*mock.Call
}

// GetMembersByTeamID is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - teamID uuid.UUID
func (_e *TeamAdapter_Expecter) GetMembersByTeamID(ctx interface{}, tx interface{}, teamID interface{}) *TeamAdapter_GetMembersByTeamID_Call {
	return &TeamAdapter_GetMembersByTeamID_Call{Call: _e.mock.On("GetMembersByTeamID", ctx, tx, teamID)}
}

func (_c *TeamAdapter_GetMembersByTeamID_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, teamID uuid.UUID)) *TeamAdapter_GetMembersByTeamID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TeamAdapter_GetMembersByTeamID_Call) Return(_a0 []*model.TeamMember, _a1 error) *TeamAdapter_GetMembersByTeamID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamAdapter_GetMembersByTeamID_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID) ([]*model.TeamMember, error)) *TeamAdapter_GetMembersByTeamID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingInvitationByTeamAndEmail provides a mock function with given fields: ctx, tx, teamID, email
func (_m *TeamAdapter) GetPendingInvitationByTeamAndEmail(ctx context.Context, tx *sqlx.Tx, teamID uuid.UUID, email string) (*model.TeamInvitation, error) {
	ret := _m.Called(ctx, tx, teamID, email)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingInvitationByTeamAndEmail")
	}

	var r0 *model.TeamInvitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, string) (*model.TeamInvitation, error)); ok {
		return rf(ctx, tx, teamID, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, string) *model.TeamInvitation); ok {
		r0 = rf(ctx, tx, teamID, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TeamInvitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, uuid.UUID, string) error); ok {
		r1 = rf(ctx, tx, teamID, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamAdapter_GetPendingInvitationByTeamAndEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingInvitationByTeamAndEmail'
type TeamAdapter_GetPendingInvitationByTeamAndEmail_Call struct {
	*mock.Call
}

// GetPendingInvitationByTeamAndEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - teamID uuid.UUID
//   - email string
func (_e *TeamAdapter_Expecter) GetPendingInvitationByTeamAndEmail(ctx interface{}, tx interface{}, teamID interface{}, email interface{}) *TeamAdapter_GetPendingInvitationByTeamAndEmail_Call {
	return &TeamAdapter_GetPendingInvitationByTeamAndEmail_Call{Call: _e.mock.On("GetPendingInvitationByTeamAndEmail", ctx, tx, teamID, email)}
}

func (_c *TeamAdapter_GetPendingInvitationByTeamAndEmail_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, teamID uuid.UUID, email string)) *TeamAdapter_GetPendingInvitationByTeamAndEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *TeamAdapter_GetPendingInvitationByTeamAndEmail_Call) Return(_a0 *model.TeamInvitation, _a1 error) *TeamAdapter_GetPendingInvitationByTeamAndEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamAdapter_GetPendingInvitationByTeamAndEmail_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID, string) (*model.TeamInvitation, error)) *TeamAdapter_GetPendingInvitationByTeamAndEmail_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function with given fields: ctx, tx, userID
func (_m *TeamAdapter) ListByUserID(ctx context.Context, tx *sqlx.Tx, userID uuid.UUID) ([]*model.TeamWithRole, error) {
	ret := _m.Called(ctx, tx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []*model.TeamWithRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID) ([]*model.TeamWithRole, error)); ok {
		return rf(ctx, tx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID) []*model.TeamWithRole); ok {
		r0 = rf(ctx, tx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.TeamWithRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamAdapter_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type TeamAdapter_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - userID uuid.UUID
func (_e *TeamAdapter_Expecter) ListByUserID(ctx interface{}, tx interface{}, userID interface{}) *TeamAdapter_ListByUserID_Call {
	return &TeamAdapter_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, tx, userID)}
}

func (_c *TeamAdapter_ListByUserID_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, userID uuid.UUID)) *TeamAdapter_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TeamAdapter_ListByUserID_Call) Return(_a0 []*model.TeamWithRole, _a1 error) *TeamAdapter_ListByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamAdapter_ListByUserID_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID) ([]*model.TeamWithRole, error)) *TeamAdapter_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewTeamAdapter creates a new instance of TeamAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamAdapter {
	mock := &TeamAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
