// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/workspace/task/model"
	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"

	uuid "github.com/google/uuid"
)

// TaskWriterRepository is an autogenerated mock type for the TaskWriterRepository type
type TaskWriterRepository struct {
	mock.Mock
}

type TaskWriterRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskWriterRepository) EXPECT() *TaskWriterRepository_Expecter {
	return &TaskWriterRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, tx, teamID, input, createdBy
func (_m *TaskWriterRepository) Create(ctx context.Context, tx *sqlx.Tx, teamID uuid.UUID, input *model.TaskInput, createdBy uuid.UUID) (*model.Task, error) {
	ret := _m.Called(ctx, tx, teamID, input, createdBy)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, *model.TaskInput, uuid.UUID) (*model.Task, error)); ok {
		return rf(ctx, tx, teamID, input, createdBy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, *model.TaskInput, uuid.UUID) *model.Task); ok {
		r0 = rf(ctx, tx, teamID, input, createdBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, uuid.UUID, *model.TaskInput, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, teamID, input, createdBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskWriterRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TaskWriterRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - teamID uuid.UUID
//   - input *model.TaskInput
//   - createdBy uuid.UUID
func (_e *TaskWriterRepository_Expecter) Create(ctx interface{}, tx interface{}, teamID interface{}, input interface{}, createdBy interface{}) *TaskWriterRepository_Create_Call {
	return &TaskWriterRepository_Create_Call{Call: _e.mock.On("Create", ctx, tx, teamID, input, createdBy)}
}

func (_c *TaskWriterRepository_Create_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, teamID uuid.UUID, input *model.TaskInput, createdBy uuid.UUID)) *TaskWriterRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID), args[3].(*model.TaskInput), args[4].(uuid.UUID))
	})
	return _c
}

func (_c *TaskWriterRepository_Create_Call) Return(_a0 *model.Task, _a1 error) *TaskWriterRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskWriterRepository_Create_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID, *model.TaskInput, uuid.UUID) (*model.Task, error)) *TaskWriterRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Restore provides a mock function with given fields: ctx, tx, taskID
func (_m *TaskWriterRepository) Restore(ctx context.Context, tx *sqlx.Tx, taskID uuid.UUID) error {
	ret := _m.Called(ctx, tx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID) error); ok {
		r0 = rf(ctx, tx, taskID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TaskWriterRepository_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type TaskWriterRepository_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - taskID uuid.UUID
func (_e *TaskWriterRepository_Expecter) Restore(ctx interface{}, tx interface{}, taskID interface{}) *TaskWriterRepository_Restore_Call {
	return &TaskWriterRepository_Restore_Call{Call: _e.mock.On("Restore", ctx, tx, taskID)}
}

func (_c *TaskWriterRepository_Restore_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, taskID uuid.UUID)) *TaskWriterRepository_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TaskWriterRepository_Restore_Call) Return(_a0 error) *TaskWriterRepository_Restore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TaskWriterRepository_Restore_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID) error) *TaskWriterRepository_Restore_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function with given fields: ctx, tx, taskID
func (_m *TaskWriterRepository) SoftDelete(ctx context.Context, tx *sqlx.Tx, taskID uuid.UUID) error {
	ret := _m.Called(ctx, tx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID) error); ok {
		r0 = rf(ctx, tx, taskID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TaskWriterRepository_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type TaskWriterRepository_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - taskID uuid.UUID
func (_e *TaskWriterRepository_Expecter) SoftDelete(ctx interface{}, tx interface{}, taskID interface{}) *TaskWriterRepository_SoftDelete_Call {
	return &TaskWriterRepository_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, tx, taskID)}
}

func (_c *TaskWriterRepository_SoftDelete_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, taskID uuid.UUID)) *TaskWriterRepository_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TaskWriterRepository_SoftDelete_Call) Return(_a0 error) *TaskWriterRepository_SoftDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TaskWriterRepository_SoftDelete_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID) error) *TaskWriterRepository_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, tx, taskID, input
func (_m *TaskWriterRepository) Update(ctx context.Context, tx *sqlx.Tx, taskID uuid.UUID, input *model.TaskInput) error {
	ret := _m.Called(ctx, tx, taskID, input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, *model.TaskInput) error); ok {
		r0 = rf(ctx, tx, taskID, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TaskWriterRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type TaskWriterRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - taskID uuid.UUID
//   - input *model.TaskInput
func (_e *TaskWriterRepository_Expecter) Update(ctx interface{}, tx interface{}, taskID interface{}, input interface{}) *TaskWriterRepository_Update_Call {
	return &TaskWriterRepository_Update_Call{Call: _e.mock.On("Update", ctx, tx, taskID, input)}
}

func (_c *TaskWriterRepository_Update_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, taskID uuid.UUID, input *model.TaskInput)) *TaskWriterRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID), args[3].(*model.TaskInput))
	})
	return _c
}

func (_c *TaskWriterRepository_Update_Call) Return(_a0 error) *TaskWriterRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TaskWriterRepository_Update_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID, *model.TaskInput) error) *TaskWriterRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewTaskWriterRepository creates a new instance of TaskWriterRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskWriterRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskWriterRepository {
	mock := &TaskWriterRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
