// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Alexander-Mandzhiev/taskflow/backend/internal/module/workspace/task/model"
	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"

	uuid "github.com/google/uuid"
)

// TaskReaderRepository is an autogenerated mock type for the TaskReaderRepository type
type TaskReaderRepository struct {
	mock.Mock
}

type TaskReaderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskReaderRepository) EXPECT() *TaskReaderRepository_Expecter {
	return &TaskReaderRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, tx, taskID
func (_m *TaskReaderRepository) GetByID(ctx context.Context, tx *sqlx.Tx, taskID uuid.UUID) (model.Task, error) {
	ret := _m.Called(ctx, tx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID) (model.Task, error)); ok {
		return rf(ctx, tx, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID) model.Task); ok {
		r0 = rf(ctx, tx, taskID)
	} else {
		r0 = ret.Get(0).(model.Task)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskReaderRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type TaskReaderRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - taskID uuid.UUID
func (_e *TaskReaderRepository_Expecter) GetByID(ctx interface{}, tx interface{}, taskID interface{}) *TaskReaderRepository_GetByID_Call {
	return &TaskReaderRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, tx, taskID)}
}

func (_c *TaskReaderRepository_GetByID_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, taskID uuid.UUID)) *TaskReaderRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TaskReaderRepository_GetByID_Call) Return(_a0 model.Task, _a1 error) *TaskReaderRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskReaderRepository_GetByID_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID) (model.Task, error)) *TaskReaderRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDIncludeDeleted provides a mock function with given fields: ctx, tx, taskID
func (_m *TaskReaderRepository) GetByIDIncludeDeleted(ctx context.Context, tx *sqlx.Tx, taskID uuid.UUID) (model.Task, error) {
	ret := _m.Called(ctx, tx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDIncludeDeleted")
	}

	var r0 model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID) (model.Task, error)); ok {
		return rf(ctx, tx, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID) model.Task); ok {
		r0 = rf(ctx, tx, taskID)
	} else {
		r0 = ret.Get(0).(model.Task)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskReaderRepository_GetByIDIncludeDeleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDIncludeDeleted'
type TaskReaderRepository_GetByIDIncludeDeleted_Call struct {
	*mock.Call
}

// GetByIDIncludeDeleted is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - taskID uuid.UUID
func (_e *TaskReaderRepository_Expecter) GetByIDIncludeDeleted(ctx interface{}, tx interface{}, taskID interface{}) *TaskReaderRepository_GetByIDIncludeDeleted_Call {
	return &TaskReaderRepository_GetByIDIncludeDeleted_Call{Call: _e.mock.On("GetByIDIncludeDeleted", ctx, tx, taskID)}
}

func (_c *TaskReaderRepository_GetByIDIncludeDeleted_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, taskID uuid.UUID)) *TaskReaderRepository_GetByIDIncludeDeleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TaskReaderRepository_GetByIDIncludeDeleted_Call) Return(_a0 model.Task, _a1 error) *TaskReaderRepository_GetByIDIncludeDeleted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskReaderRepository_GetByIDIncludeDeleted_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID) (model.Task, error)) *TaskReaderRepository_GetByIDIncludeDeleted_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, tx, filter
func (_m *TaskReaderRepository) List(ctx context.Context, tx *sqlx.Tx, filter model.TaskListFilter) ([]model.Task, int, error) {
	ret := _m.Called(ctx, tx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Task
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, model.TaskListFilter) ([]model.Task, int, error)); ok {
		return rf(ctx, tx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, model.TaskListFilter) []model.Task); ok {
		r0 = rf(ctx, tx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, model.TaskListFilter) int); ok {
		r1 = rf(ctx, tx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *sqlx.Tx, model.TaskListFilter) error); ok {
		r2 = rf(ctx, tx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// TaskReaderRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type TaskReaderRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - filter model.TaskListFilter
func (_e *TaskReaderRepository_Expecter) List(ctx interface{}, tx interface{}, filter interface{}) *TaskReaderRepository_List_Call {
	return &TaskReaderRepository_List_Call{Call: _e.mock.On("List", ctx, tx, filter)}
}

func (_c *TaskReaderRepository_List_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, filter model.TaskListFilter)) *TaskReaderRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(model.TaskListFilter))
	})
	return _c
}

func (_c *TaskReaderRepository_List_Call) Return(_a0 []model.Task, _a1 int, _a2 error) *TaskReaderRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *TaskReaderRepository_List_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, model.TaskListFilter) ([]model.Task, int, error)) *TaskReaderRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewTaskReaderRepository creates a new instance of TaskReaderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskReaderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskReaderRepository {
	mock := &TaskReaderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
